import express from "express";
import fetch from "node-fetch";
import "dotenv/config";
const VERSION="2026-09-09-g83-replacement-standalone-live-v1.0.0";
const MP="A1VC38T7YXB528",PT="NOTEBOOK_COMPUTER",SOURCE_SKU="SO-9QJ3-7SHR",SOURCE_ASIN="B0FPC2JKBY";
const TARGETS=[
 {key:"ssd256",sku:"g83-hs-i5-11g-8gb-ssd256-r1",ean:"4595989934973",target:256,title:"【整備済み品】ダイナブック G83/HS 中古ノートパソコン 13.3型FHD 第11世代 Core i5-1135G7 メモリ8GB SSD256GB Windows 11 Pro MS Office 2024 Webカメラ Wi-Fi6 ノートン360付属 MTD整備済み"},
 {key:"ssd1tb",sku:"g83-hs-i5-11g-8gb-ssd1tb-r1",ean:"4595989934980",target:1024,title:"【整備済み品】ダイナブック G83/HS 中古ノートパソコン 13.3型FHD 第11世代 Core i5-1135G7 メモリ8GB SSD1TB Windows 11 Pro MS Office 2024 Webカメラ Wi-Fi6 ノートン360付属 MTD整備済み"}
];
const FAMILY=["F7-AF7O-IGX5",SOURCE_SKU,"9K-D0RA-4R8V","E7-YLJ3-F9CY","5K-G098-FO9O","QH-ITJ6-BTTC"];
const oldListen=express.application.listen,clone=v=>JSON.parse(JSON.stringify(v)),jp=t=>{try{return t?JSON.parse(t):{};}catch{return{rawText:String(t||"").slice(0,3000)}}},sleep=ms=>new Promise(r=>setTimeout(r,ms));
function cfg(){const sellerId=String(process.env.SPAPI_SELLER_ID||"").trim(),marketplaceId=String(process.env.SPAPI_MARKETPLACE_ID||MP).trim(),endpoint=String(process.env.SPAPI_ENDPOINT||"https://sellingpartnerapi-fe.amazon.com").replace(/\/$/,"");if(!sellerId)throw new Error("Missing SPAPI_SELLER_ID");if(marketplaceId!==MP)throw new Error(`MARKETPLACE_MISMATCH:${marketplaceId}`);return{sellerId,marketplaceId,endpoint};}
async function ft(url,opt={}){const c=new AbortController(),tm=setTimeout(()=>c.abort(),30000);try{return await fetch(url,{...opt,signal:c.signal})}finally{clearTimeout(tm)}}
async function token(){const r=await ft("https://api.amazon.com/auth/o2/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({grant_type:"refresh_token",refresh_token:process.env.REFRESH_TOKEN,client_id:process.env.LWA_CLIENT_ID,client_secret:process.env.LWA_CLIENT_SECRET})});const x=jp(await r.text());if(!r.ok||!x.access_token)throw new Error(`LWA_${r.status}`);return x.access_token;}
async function req(url,a,opt={}){const r=await ft(url,{method:opt.method||"GET",headers:{"x-amz-access-token":a,accept:"application/json",...(opt.body?{"content-type":"application/json"}:{})},...(opt.body?{body:JSON.stringify(opt.body)}:{})});return{http:r.status,ok:r.ok,body:jp(await r.text())};}
async function listing(a,sku){const {sellerId,marketplaceId,endpoint}=cfg();const q=new URLSearchParams({marketplaceIds:marketplaceId,includedData:"summaries,attributes,issues",issueLocale:"ja_JP"});return req(`${endpoint}/listings/2021-08-01/items/${encodeURIComponent(sellerId)}/${encodeURIComponent(sku)}?${q}`,a);}
async function schema(a){const {sellerId,marketplaceId,endpoint}=cfg();const q=new URLSearchParams({sellerId,marketplaceIds:marketplaceId,requirements:"LISTING",requirementsEnforced:"ENFORCED",locale:"ja_JP"});const d=await req(`${endpoint}/definitions/2020-09-01/productTypes/${PT}?${q}`,a);if(!d.ok)throw new Error(`PTD_${d.http}`);const u=String(d.body?.schema?.link?.resource||"");const r=await ft(u,{headers:{accept:"application/json"}});if(!r.ok)throw new Error(`PTD_SCHEMA_${r.status}`);return jp(await r.text());}
function vals(n){const o=[];(function w(v,d){if(!v||typeof v!=="object"||d>14)return;if(Array.isArray(v)){v.forEach(x=>w(x,d+1));return}if(Array.isArray(v.enum))o.push(...v.enum.map(String));if(v.const!==undefined)o.push(String(v.const));if(v.properties&&typeof v.properties==="object")Object.values(v.properties).forEach(x=>w(x,d+1));if(v.items)w(v.items,d+1);for(const k of["oneOf","anyOf","allOf"])if(Array.isArray(v[k]))v[k].forEach(x=>w(x,d+1))})(n,0);return[...new Set(o)];}
function measure(rows,key){return Array.isArray(rows)&&rows[0]&&Array.isArray(rows[0]?.[key])&&rows[0][key][0]?rows[0][key][0]:null;}
function gb(x){if(!x)return null;const n=Number(x.value),u=String(x.unit||"GB").toUpperCase();return!Number.isFinite(n)?null:u==="TB"?n*1024:u==="MB"?n/1024:n;}
function setStorage(rows,key,target){const x=clone(rows||[]),m=key==="hard_disk"?x?.[0]?.size?.[0]:x?.[0]?.installed_size?.[0];if(!m)throw new Error(`${key}_SHAPE`);m.value=target===1024?1:target;m.unit=target===1024?"TB":"GB";return x;}
function replace512(v,to){if(typeof v==="string")return v.split("512GB").join(to);if(Array.isArray(v))return v.map(x=>replace512(x,to));if(v&&typeof v==="object"){const o={};for(const[k,x]of Object.entries(v))o[k]=replace512(x,to);return o}return v;}
const ids=a=>(Array.isArray(a?.externally_assigned_product_identifier)?a.externally_assigned_product_identifier:[]).map(x=>String(x?.value||"").trim()).filter(Boolean);
function relation(a){return{parentage:a?.parentage_level?.[0]?.value||null,parentSku:a?.child_parent_sku_relationship?.[0]?.parent_sku||null,theme:a?.variation_theme?.[0]?.name||null};}
function build(src,t,cell,type,idType,installType){const a=clone(src);for(const k of["externally_assigned_product_identifier","merchant_suggested_asin","supplier_declared_has_product_identifier_exemption","purchasable_offer","fulfillment_availability","list_price","minimum_seller_allowed_price","maximum_seller_allowed_price","merchant_shipping_group","parentage_level","child_parent_sku_relationship","variation_theme"])delete a[k];for(const k of Object.keys(a))if(/main_product_image_locator|other_product_image_locator|swatch_product_image_locator/i.test(k))delete a[k];a.hard_disk=setStorage(a.hard_disk,"hard_disk",t.target);a.flash_memory=setStorage(a.flash_memory,"flash_memory",t.target);for(const k of["item_name","bullet_point","product_description","generic_keyword","size"])if(a[k])a[k]=replace512(a[k],t.target===1024?"1TB":"256GB");if(a.item_name?.[0])a.item_name[0].value=t.title;a.externally_assigned_product_identifier=[{marketplace_id:MP,type:idType,value:t.ean}];a.is_exclusive_product=[{marketplace_id:MP,value:false}];a.skip_offer=[{marketplace_id:MP,value:true}];a.batteries_required=[{marketplace_id:MP,value:false}];a.batteries_included=[{marketplace_id:MP,value:true}];a.battery=[{marketplace_id:MP,cell_composition:[{value:cell}],weight:[{value:211,unit:"grams"}]}];a.num_batteries=[{marketplace_id:MP,quantity:1,type}];a.has_multiple_battery_powered_components=[{marketplace_id:MP,value:false}];a.contains_battery_or_cell=[{marketplace_id:MP,value:"battery"}];a.number_of_lithium_ion_cells=[{marketplace_id:MP,value:4}];a.lithium_battery=[{marketplace_id:MP,energy_content:[{value:53,unit:"watt_hours"}],packaging:[{value:"batteries_contained_in_equipment"}],weight:[{value:211,unit:"grams"}]}];a.battery_installation_device_type=[{marketplace_id:MP,value:installType}];a.item_package_dimensions=[{marketplace_id:MP,length:{value:38.5,unit:"centimeters"},width:{value:27.5,unit:"centimeters"},height:{value:14,unit:"centimeters"}}];a.item_package_weight=[{marketplace_id:MP,value:1.9,unit:"kilograms"}];return a;}
function clean(a){const s=JSON.stringify(a);return!["TOSHIBA","東芝","B0FN3KQFR3","B0FPC4R7ZG","F7-AF7O-IGX5","9K-D0RA-4R8V"].some(t=>new RegExp(t,"i").test(s));}
async function put(a,sku,attrs,preview=false){const {sellerId,marketplaceId,endpoint}=cfg();const q=new URLSearchParams({marketplaceIds:marketplaceId,issueLocale:"ja_JP",includedData:"issues",...(preview?{mode:"VALIDATION_PREVIEW"}:{})});return req(`${endpoint}/listings/2021-08-01/items/${encodeURIComponent(sellerId)}/${encodeURIComponent(sku)}?${q}`,a,{method:"PUT",body:{productType:PT,requirements:"LISTING",attributes:attrs}});}
function validate(r){const issues=Array.isArray(r?.body?.issues)?r.body.issues:[],errors=issues.filter(i=>String(i?.severity||"").toUpperCase()==="ERROR"),status=String(r?.body?.status||"").toUpperCase();return{httpStatus:r.http,status,errorCount:errors.length,errors:errors.map(i=>({code:i.code,message:i.message,attributeNames:i.attributeNames||[]})),valid:r.ok&&errors.length===0&&["VALID","ACCEPTED"].includes(status)};}
function snapshot(t,r){if(!r.ok)return{sku:t.sku,exists:false,httpStatus:r.http};const s=r.body?.summaries?.[0]||{},a=r.body?.attributes||{},issues=Array.isArray(r.body?.issues)?r.body.issues:[];return{sku:t.sku,exists:true,asin:String(s.asin||""),productType:String(s.productType||""),ean:ids(a)[0]||null,ramGB:gb(measure(a?.ram_memory,"installed_size")),storageGB:gb(measure(a?.hard_disk,"size")),relation:relation(a),errorCount:issues.filter(i=>String(i?.severity||"").toUpperCase()==="ERROR").length,issueCodes:[...new Set(issues.map(i=>String(i?.code||"")).filter(Boolean))]};}
function exactExisting(t,s){return s.exists&&s.productType===PT&&s.ean===t.ean&&s.ramGB===8&&s.storageGB===t.target&&!s.relation.parentSku&&s.errorCount===0;}
async function run(){const a=await token(),src=await listing(a,SOURCE_SKU);if(!src.ok)throw new Error(`SOURCE_${src.http}`);const sm=src.body?.summaries?.[0]||{},at=src.body?.attributes||{},issues=Array.isArray(src.body?.issues)?src.body.issues:[];if(String(sm.asin||"")!==SOURCE_ASIN||gb(measure(at?.ram_memory,"installed_size"))!==8||gb(measure(at?.hard_disk,"size"))!==512||issues.some(i=>String(i?.severity||"").toUpperCase()==="ERROR"))throw new Error("SOURCE_FRESH_GUARD_BLOCK");for(const sku of FAMILY){const r=await listing(a,sku);if(r.ok)for(const id of ids(r.body?.attributes||{}))if(TARGETS.some(t=>t.ean===id))throw new Error(`EAN_REUSE_BLOCKED:${id}`)}const sc=await schema(a),batteryVals=vals(sc?.properties?.battery),numVals=vals(sc?.properties?.num_batteries),idVals=vals(sc?.properties?.externally_assigned_product_identifier),installVals=vals(sc?.properties?.battery_installation_device_type);const cell=["lithium_polymer","lithium_ion"].find(x=>batteryVals.includes(x)),type=numVals.includes("nonstandard_battery")?"nonstandard_battery":null,idType=idVals.find(x=>/^ean$/i.test(x))||"ean",installType=installVals.includes("not_installed")?"not_installed":null;if(!cell||!type||!installType)throw new Error("SCHEMA_RESOLUTION_BLOCK");let writes=0;const actions=[];for(const t of TARGETS){let g=await listing(a,t.sku),s=snapshot(t,g);if(g.ok){if(!exactExisting(t,s))throw new Error(`EXISTING_TARGET_GUARD_BLOCK:${t.sku}:${JSON.stringify(s)}`);actions.push({key:t.key,action:"PRESERVE_EXISTING_EXACT",snapshot:s});continue}if(g.http!==404)throw new Error(`TARGET_PREFLIGHT_${t.sku}_${g.http}`);const attrs=build(at,t,cell,type,idType,installType);if(!clean(attrs))throw new Error(`CLEAN_ROOM_BLOCK:${t.sku}`);const pv=validate(await put(a,t.sku,attrs,true));if(!pv.valid)throw new Error(`PREVIEW_BLOCK:${t.sku}:${JSON.stringify(pv)}`);const live=await put(a,t.sku,attrs,false),lv=validate(live);if(!live.ok||lv.errorCount)throw new Error(`LIVE_PUT_BLOCK:${t.sku}:${JSON.stringify(lv)}`);writes++;actions.push({key:t.key,action:"LIVE_PUT_ACCEPTED",live:lv});}
let final=[];for(let i=0;i<12;i++){final=[];let all=true;for(const t of TARGETS){const s=snapshot(t,await listing(a,t.sku));final.push(s);if(!exactExisting(t,s)||!s.asin)all=false;}if(all)break;await sleep(5000)}const allHealthy=final.length===2&&TARGETS.every(t=>{const s=final.find(x=>x.sku===t.sku);return exactExisting(t,s)&&Boolean(s.asin)});return{status:allHealthy?"G83_REPLACEMENT_STANDALONE_2_OF_2_HEALTHY":"G83_REPLACEMENT_STANDALONE_PENDING_OR_BLOCK",moduleVersion:VERSION,actions,final,amazonPersistentWrites:writes,inventoryWrites:0,priceWrites:0,b2bWrites:0,adsWrites:0,yahooWrites:0,externalChanges:writes,readyForRelationshipAttachment:allHealthy};}
express.application.listen=function(...args){const server=oldListen.apply(this,args);setTimeout(async()=>{try{const out=await run();console.log(`G83_REPLACEMENT_STANDALONE_LIVE_RESULT=${JSON.stringify(out)}`)}catch(e){console.error(`G83_REPLACEMENT_STANDALONE_LIVE_ERROR=${JSON.stringify({moduleVersion:VERSION,error:e?.message||String(e),inventoryWrites:0,priceWrites:0,yahooWrites:0})}`)}},5000);return server};
