import express from "express";
import fetch from "node-fetch";
import "dotenv/config";

const MODULE_VERSION="2026-09-13-g83-replacement-b2c-price-preview-v1.0.0";
const ROUTE="/amazon/price/g83-replacement/b2c-validation-preview";
const TOKEN="G83_REPLACEMENT_B2C_PRICE_PREVIEW_20260913_V1";
const MARKETPLACE="A1VC38T7YXB528";
const originalListen=express.application.listen;
const TARGETS=Object.freeze([
 {sku:"g83-hs-i5-11g-8gb-ssd256-r1",asin:"B0HJ8L6KJY",price:38100,min:24800},
 {sku:"g83-hs-i5-11g-8gb-ssd1tb-r1",asin:"B0HJ8SKQGG",price:58100,min:53300}
]);
const parse=t=>{try{return t?JSON.parse(t):{};}catch{return{rawText:String(t||"").slice(0,1200)}}};
const clone=v=>JSON.parse(JSON.stringify(v));
const audience=o=>String(o?.audience||"ALL").toUpperCase();
function cfg(){const sellerId=String(process.env.SPAPI_SELLER_ID||"").trim();if(!sellerId)throw new Error("Missing SPAPI_SELLER_ID");return{sellerId,marketplaceId:String(process.env.SPAPI_MARKETPLACE_ID||MARKETPLACE).trim(),endpoint:String(process.env.SPAPI_ENDPOINT||"https://sellingpartnerapi-fe.amazon.com").replace(/\/$/,"")};}
async function lwa(){const{LWA_CLIENT_ID:client_id,LWA_CLIENT_SECRET:client_secret,REFRESH_TOKEN:refresh_token}=process.env;if(!client_id||!client_secret||!refresh_token)throw new Error("Missing LWA env");const r=await fetch("https://api.amazon.com/auth/o2/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({grant_type:"refresh_token",refresh_token,client_id,client_secret})});const j=parse(await r.text());if(!r.ok||!j.access_token)throw new Error(`LWA ${r.status}`);return j.access_token;}
async function request(url,opt){const r=await fetch(url,opt);const j=parse(await r.text());if(!r.ok)throw new Error(`SPAPI ${r.status} ${JSON.stringify(j).slice(0,1800)}`);return{r,j};}
async function getListing(a,sku){const{sellerId,marketplaceId,endpoint}=cfg();const q=new URLSearchParams({marketplaceIds:marketplaceId,includedData:"summaries,attributes,issues,offers,fulfillmentAvailability",issueLocale:"ja_JP"});return(await request(`${endpoint}/listings/2021-08-01/items/${encodeURIComponent(sellerId)}/${encodeURIComponent(sku)}?${q}`,{headers:{"x-amz-access-token":a,accept:"application/json"}})).j;}
function val(o,k){const n=Number(o?.[k]?.[0]?.schedule?.[0]?.value_with_tax);return Number.isFinite(n)?n:null;}
function makeConsumer(t,m){return{currency:"JPY",audience:"ALL",our_price:[{schedule:[{value_with_tax:t.price}]}],minimum_seller_allowed_price:[{schedule:[{value_with_tax:t.min}]}],marketplace_id:m};}
async function preview(a,t,listing){const{sellerId,marketplaceId,endpoint}=cfg();const s=Array.isArray(listing?.summaries)?listing.summaries[0]||{}:{};if(String(s.asin||"")!==t.asin)throw new Error(`ASIN_MISMATCH ${t.sku}`);const before=clone(Array.isArray(listing?.attributes?.purchasable_offer)?listing.attributes.purchasable_offer:[]);const beforeB2B=before.filter(x=>audience(x)==="B2B");const after=clone(before);let i=after.findIndex(x=>audience(x)!=="B2B");if(i<0){after.push(makeConsumer(t,marketplaceId));i=after.length-1;}else{after[i].currency=after[i].currency||"JPY";after[i].audience=after[i].audience||"ALL";after[i].marketplace_id=after[i].marketplace_id||marketplaceId;after[i].our_price=[{schedule:[{value_with_tax:t.price}]}];after[i].minimum_seller_allowed_price=[{schedule:[{value_with_tax:t.min}]}];}if(JSON.stringify(beforeB2B)!==JSON.stringify(after.filter(x=>audience(x)==="B2B")))throw new Error(`B2B_MUTATION ${t.sku}`);const q=new URLSearchParams({marketplaceIds:marketplaceId,issueLocale:"ja_JP",mode:"VALIDATION_PREVIEW"});const body={productType:String(s.productType||"NOTEBOOK_COMPUTER"),patches:[{op:"replace",path:"/attributes/purchasable_offer",value:after}]};const{r,j}=await request(`${endpoint}/listings/2021-08-01/items/${encodeURIComponent(sellerId)}/${encodeURIComponent(t.sku)}?${q}`,{method:"PATCH",headers:{"x-amz-access-token":a,accept:"application/json","content-type":"application/json"},body:JSON.stringify(body)});const issues=Array.isArray(j?.issues)?j.issues:[];const errors=issues.filter(x=>String(x?.severity||"").toUpperCase()==="ERROR");const c=before.find(x=>audience(x)!=="B2B")||null;return{sku:t.sku,asin:t.asin,currentPrice:val(c,"our_price"),currentMin:val(c,"minimum_seller_allowed_price"),targetPrice:t.price,targetMin:t.min,statuses:Array.isArray(s.status)?s.status:[],listingErrorCount:(Array.isArray(listing?.issues)?listing.issues:[]).filter(x=>String(x?.severity||"").toUpperCase()==="ERROR").length,b2bPreserved:JSON.stringify(beforeB2B)===JSON.stringify(after.filter(x=>audience(x)==="B2B")),httpStatus:r.status,responseStatus:String(j?.status||""),submissionId:String(j?.submissionId||""),previewIssueCodes:issues.map(x=>String(x?.code||"")).filter(Boolean),validationPassed:r.ok&&errors.length===0,externalChanges:0};}
async function handler(req,res){try{const sec=String(process.env.AMAZON_STOCK_API_SECRET||"").trim();if(!sec)return res.status(500).json({ok:false,externalChanges:0,error:"secret missing"});if(String(req.headers["x-api-secret"]||"")!==sec)return res.status(401).json({ok:false,externalChanges:0,error:"Unauthorized"});if(String(req.body?.batchToken||"")!==TOKEN)throw new Error("GUARD_BLOCKED invalid batchToken");if(req.body?.dryRun===false)throw new Error("LIVE_DISABLED validation preview only");const a=await lwa();const results=[];for(const t of TARGETS)results.push(await preview(a,t,await getListing(a,t.sku)));const passed=results.filter(x=>x.validationPassed&&x.b2bPreserved).length;return res.status(200).json({ok:passed===TARGETS.length,moduleVersion:MODULE_VERSION,route:ROUTE,batchToken:TOKEN,decision:passed===TARGETS.length?"G83_REPLACEMENT_B2C_PRICE_PREVIEW_ALL_2_PASS":"G83_REPLACEMENT_B2C_PRICE_PREVIEW_HAS_ERRORS",previewCalls:results.length,validationPassedCount:passed,validationFailedCount:results.length-passed,safety:{mode:"VALIDATION_PREVIEW",persistentAmazonWrites:0,liveCalls:0,externalChanges:0},results,externalChanges:0});}catch(e){return res.status(400).json({ok:false,moduleVersion:MODULE_VERSION,route:ROUTE,decision:"STOP_EXCEPTION",externalChanges:0,error:e?.message||String(e)});}}
express.application.listen=function g83ReplacementB2CPricePreviewListen(...args){const exists=Boolean(this?._router?.stack?.some(l=>l?.route?.path===ROUTE));if(!exists)this.post(ROUTE,handler);return originalListen.apply(this,args);};
