import express from "express";
import fetch from "node-fetch";
import "dotenv/config";

const MODULE_VERSION="2026-09-13-g83-hs-six-b2c-price-preview-v2.0.0";
const ROUTE="/amazon/price/g83-replacement/b2c-validation-preview";
const TOKEN="G83_HS_B2C_PRICE_6_PREVIEW_20260913_V2";
const MARKETPLACE="A1VC38T7YXB528";
const originalListen=express.application.listen;
const TARGETS=Object.freeze([
 {sku:"g83-hs-i5-11g-8gb-ssd256-r1",asin:"B0HJ8L6KJY",price:35800,min:25200,currentPrice:null,currentMin:null,points:null},
 {sku:"SO-9QJ3-7SHR",asin:"B0FPC2JKBY",price:45800,min:40100,currentPrice:77000,currentMin:39400,points:770},
 {sku:"g83-hs-i5-11g-8gb-ssd1tb-r1",asin:"B0HJ8SKQGG",price:55800,min:54100,currentPrice:null,currentMin:null,points:null},
 {sku:"E7-YLJ3-F9CY",asin:"B0GZBHBQN2",price:43800,min:36700,currentPrice:43800,currentMin:36200,points:438},
 {sku:"5K-G098-FO9O",asin:"B0FPC52B8K",price:53800,min:51500,currentPrice:78000,currentMin:50800,points:780},
 {sku:"QH-ITJ6-BTTC",asin:"B0FPC385LM",price:66800,min:65900,currentPrice:87000,currentMin:65200,points:870}
]);
const parse=t=>{try{return t?JSON.parse(t):{};}catch{return{rawText:String(t||"").slice(0,1200)}}};
const clone=v=>JSON.parse(JSON.stringify(v));
const audience=o=>String(o?.audience||"ALL").toUpperCase();
const offerType=o=>String(o?.offerType||o?.offer_type||"").toUpperCase();
function num(v){if(v===null||v===undefined||v==="")return null;if(typeof v==="object"){for(const k of ["pointsNumber","PointsNumber","points_number","amount","Amount","value","Value"]){const n=num(v?.[k]);if(n!==null)return n;}return null;}const n=Number(v);return Number.isFinite(n)?n:null;}
function cfg(){const sellerId=String(process.env.SPAPI_SELLER_ID||"").trim();if(!sellerId)throw new Error("Missing SPAPI_SELLER_ID");return{sellerId,marketplaceId:String(process.env.SPAPI_MARKETPLACE_ID||MARKETPLACE).trim(),endpoint:String(process.env.SPAPI_ENDPOINT||"https://sellingpartnerapi-fe.amazon.com").replace(/\/$/,"")};}
async function lwa(){const{LWA_CLIENT_ID:client_id,LWA_CLIENT_SECRET:client_secret,REFRESH_TOKEN:refresh_token}=process.env;if(!client_id||!client_secret||!refresh_token)throw new Error("Missing LWA env");const r=await fetch("https://api.amazon.com/auth/o2/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({grant_type:"refresh_token",refresh_token,client_id,client_secret})});const j=parse(await r.text());if(!r.ok||!j.access_token)throw new Error(`LWA ${r.status}`);return j.access_token;}
async function request(url,opt){const r=await fetch(url,opt);const j=parse(await r.text());if(!r.ok)throw new Error(`SPAPI ${r.status} ${JSON.stringify(j).slice(0,1800)}`);return{r,j};}
async function getListing(a,sku){const{sellerId,marketplaceId,endpoint}=cfg();const q=new URLSearchParams({marketplaceIds:marketplaceId,includedData:"summaries,attributes,issues,offers,fulfillmentAvailability",issueLocale:"ja_JP"});return(await request(`${endpoint}/listings/2021-08-01/items/${encodeURIComponent(sellerId)}/${encodeURIComponent(sku)}?${q}`,{headers:{"x-amz-access-token":a,accept:"application/json"}})).j;}
function val(o,k){return num(o?.[k]?.[0]?.schedule?.[0]?.value_with_tax);}
function actualPoints(listing){const offers=Array.isArray(listing?.offers)?listing.offers:[];const b2c=offers.find(o=>offerType(o)==="B2C"||audience(o)==="ALL")||null;return b2c&&Object.prototype.hasOwnProperty.call(b2c,"points")?num(b2c.points):null;}
function setValue(offer,key,value){if(Array.isArray(offer?.[key])&&offer[key][0]&&Array.isArray(offer[key][0].schedule)&&offer[key][0].schedule[0])offer[key][0].schedule[0].value_with_tax=value;else offer[key]=[{schedule:[{value_with_tax:value}]}];}
function makeConsumer(t,m){return{currency:"JPY",audience:"ALL",our_price:[{schedule:[{value_with_tax:t.price}]}],minimum_seller_allowed_price:[{schedule:[{value_with_tax:t.min}]}],marketplace_id:m};}
function protectedConsumer(o){const x=clone(o||{});delete x.our_price;delete x.minimum_seller_allowed_price;return x;}
async function preview(a,t,listing){const{sellerId,marketplaceId,endpoint}=cfg();const s=Array.isArray(listing?.summaries)?listing.summaries[0]||{}:{};if(String(s.asin||"")!==t.asin)throw new Error(`ASIN_MISMATCH ${t.sku}`);const before=clone(Array.isArray(listing?.attributes?.purchasable_offer)?listing.attributes.purchasable_offer:[]);const c0=before.find(x=>audience(x)!=="B2B")||null;const p0=actualPoints(listing);if(val(c0,"our_price")!==t.currentPrice)throw new Error(`CURRENT_PRICE_MISMATCH ${t.sku} expected=${t.currentPrice} actual=${val(c0,"our_price")}`);if(val(c0,"minimum_seller_allowed_price")!==t.currentMin)throw new Error(`CURRENT_MIN_MISMATCH ${t.sku} expected=${t.currentMin} actual=${val(c0,"minimum_seller_allowed_price")}`);if(p0!==t.points)throw new Error(`POINTS_MISMATCH ${t.sku} expected=${t.points} actual=${p0}`);const beforeB2B=before.filter(x=>audience(x)==="B2B");const after=clone(before);let i=after.findIndex(x=>audience(x)!=="B2B");if(i<0){after.push(makeConsumer(t,marketplaceId));i=after.length-1;}else{const protectedBefore=JSON.stringify(protectedConsumer(after[i]));after[i].currency=after[i].currency||"JPY";after[i].audience=after[i].audience||"ALL";after[i].marketplace_id=after[i].marketplace_id||marketplaceId;setValue(after[i],"our_price",t.price);setValue(after[i],"minimum_seller_allowed_price",t.min);if(JSON.stringify(protectedConsumer(after[i]))!==protectedBefore)throw new Error(`CONSUMER_PROTECTED_MUTATION ${t.sku}`);}if(JSON.stringify(beforeB2B)!==JSON.stringify(after.filter(x=>audience(x)==="B2B")))throw new Error(`B2B_MUTATION ${t.sku}`);const q=new URLSearchParams({marketplaceIds:marketplaceId,issueLocale:"ja_JP",mode:"VALIDATION_PREVIEW"});const body={productType:String(s.productType||"NOTEBOOK_COMPUTER"),patches:[{op:"replace",path:"/attributes/purchasable_offer",value:after}]};const{r,j}=await request(`${endpoint}/listings/2021-08-01/items/${encodeURIComponent(sellerId)}/${encodeURIComponent(t.sku)}?${q}`,{method:"PATCH",headers:{"x-amz-access-token":a,accept:"application/json","content-type":"application/json"},body:JSON.stringify(body)});const issues=Array.isArray(j?.issues)?j.issues:[];const errors=issues.filter(x=>String(x?.severity||"").toUpperCase()==="ERROR");return{sku:t.sku,asin:t.asin,currentPrice:t.currentPrice,currentMin:t.currentMin,currentPoints:p0,targetPrice:t.price,targetMin:t.min,statuses:Array.isArray(s.status)?s.status:[],listingErrorCount:(Array.isArray(listing?.issues)?listing.issues:[]).filter(x=>String(x?.severity||"").toUpperCase()==="ERROR").length,b2bPreserved:JSON.stringify(beforeB2B)===JSON.stringify(after.filter(x=>audience(x)==="B2B")),consumerProtectedFieldsPreserved:true,pointsPathNotPatched:true,httpStatus:r.status,responseStatus:String(j?.status||""),submissionId:String(j?.submissionId||""),previewIssueCodes:issues.map(x=>String(x?.code||"")).filter(Boolean),validationPassed:r.ok&&errors.length===0,externalChanges:0};}
async function handler(req,res){try{const sec=String(process.env.AMAZON_STOCK_API_SECRET||"").trim();if(!sec)return res.status(500).json({ok:false,externalChanges:0,error:"secret missing"});if(String(req.headers["x-api-secret"]||"")!==sec)return res.status(401).json({ok:false,externalChanges:0,error:"Unauthorized"});if(String(req.body?.batchToken||"")!==TOKEN)throw new Error("GUARD_BLOCKED invalid batchToken");if(req.body?.dryRun===false)throw new Error("LIVE_DISABLED validation preview only");const a=await lwa();const listings=[];for(const t of TARGETS)listings.push([t,await getListing(a,t.sku)]);const results=[];for(const [t,l] of listings)results.push(await preview(a,t,l));const passed=results.filter(x=>x.validationPassed&&x.b2bPreserved&&x.consumerProtectedFieldsPreserved).length;return res.status(200).json({ok:passed===TARGETS.length,moduleVersion:MODULE_VERSION,route:ROUTE,batchToken:TOKEN,decision:passed===TARGETS.length?"G83_HS_B2C_PRICE_PREVIEW_ALL_6_PASS":"G83_HS_B2C_PRICE_PREVIEW_HAS_ERRORS",previewCalls:results.length,validationPassedCount:passed,validationFailedCount:results.length-passed,safety:{mode:"VALIDATION_PREVIEW",persistentAmazonWrites:0,liveCalls:0,externalChanges:0},matrixChecks:{storageMonotonic8gb:TARGETS[0].price<TARGETS[1].price&&TARGETS[1].price<TARGETS[2].price,storageMonotonic16gb:TARGETS[3].price<TARGETS[4].price&&TARGETS[4].price<TARGETS[5].price,ramPremium256:TARGETS[3].price>TARGETS[0].price,ramPremium512:TARGETS[4].price>TARGETS[1].price,ramPremium1tb:TARGETS[5].price>TARGETS[2].price},results,externalChanges:0});}catch(e){return res.status(409).json({ok:false,moduleVersion:MODULE_VERSION,route:ROUTE,decision:"STOP_FAIL_CLOSED",safety:{persistentAmazonWrites:0,liveCalls:0,externalChanges:0},externalChanges:0,error:e?.message||String(e)});}}
express.application.listen=function g83HsSixB2CPricePreviewListen(...args){const exists=Boolean(this?._router?.stack?.some(l=>l?.route?.path===ROUTE));if(!exists)this.post(ROUTE,handler);return originalListen.apply(this,args);};
