import express from "express";
import fetch from "node-fetch";
import "dotenv/config";
const VERSION="2026-09-09-g83-replacement-validation-preview-v1.0.6";
const ROUTE="/amazon/listing/g83-replacement-validation-preview-v106";
const MP="A1VC38T7YXB528",PT="NOTEBOOK_COMPUTER",SOURCE_SKU="SO-9QJ3-7SHR",SOURCE_ASIN="B0FPC2JKBY";
const SKU256="g83-hs-i5-11g-8gb-ssd256-r1",SKU1TB="g83-hs-i5-11g-8gb-ssd1tb-r1";
const EAN256="4595989934973",EAN1TB="4595989934980";
const FAMILY=["F7-AF7O-IGX5",SOURCE_SKU,"9K-D0RA-4R8V","E7-YLJ3-F9CY","5K-G098-FO9O","QH-ITJ6-BTTC"];
const oldListen=express.application.listen;
const clone=v=>JSON.parse(JSON.stringify(v));
const jp=t=>{try{return t?JSON.parse(t):{};}catch{return{rawText:String(t||"").slice(0,3000)}}};
function cfg(){const sellerId=String(process.env.SPAPI_SELLER_ID||"").trim(),marketplaceId=String(process.env.SPAPI_MARKETPLACE_ID||MP).trim(),endpoint=String(process.env.SPAPI_ENDPOINT||"https://sellingpartnerapi-fe.amazon.com").replace(/\/$/,"");if(!sellerId)throw new Error("Missing SPAPI_SELLER_ID");if(marketplaceId!==MP)throw new Error(`MARKETPLACE_MISMATCH:${marketplaceId}`);return{sellerId,marketplaceId,endpoint};}
async function ft(url,opt={}){const c=new AbortController(),tm=setTimeout(()=>c.abort(),25000);try{return await fetch(url,{...opt,signal:c.signal})}finally{clearTimeout(tm)}}
async function token(){const r=await ft("https://api.amazon.com/auth/o2/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({grant_type:"refresh_token",refresh_token:process.env.REFRESH_TOKEN,client_id:process.env.LWA_CLIENT_ID,client_secret:process.env.LWA_CLIENT_SECRET})});const x=jp(await r.text());if(!r.ok||!x.access_token)throw new Error(`LWA_${r.status}`);return x.access_token;}
async function req(url,a,opt={}){const r=await ft(url,{method:opt.method||"GET",headers:{"x-amz-access-token":a,accept:"application/json",...(opt.body?{"content-type":"application/json"}:{})},...(opt.body?{body:JSON.stringify(opt.body)}:{})});return{http:r.status,ok:r.ok,body:jp(await r.text())};}
async function listing(a,sku){const {sellerId,marketplaceId,endpoint}=cfg();const q=new URLSearchParams({marketplaceIds:marketplaceId,includedData:"summaries,attributes,issues",issueLocale:"ja_JP"});return req(`${endpoint}/listings/2021-08-01/items/${encodeURIComponent(sellerId)}/${encodeURIComponent(sku)}?${q}`,a);}
async function schema(a){const {sellerId,marketplaceId,endpoint}=cfg();const q=new URLSearchParams({sellerId,marketplaceIds:marketplaceId,requirements:"LISTING",requirementsEnforced:"ENFORCED",locale:"ja_JP"});const d=await req(`${endpoint}/definitions/2020-09-01/productTypes/${PT}?${q}`,a);if(!d.ok)throw new Error(`PTD_${d.http}`);const u=String(d.body?.schema?.link?.resource||"");if(!u)throw new Error("PTD_SCHEMA_LINK_MISSING");const r=await ft(u,{headers:{accept:"application/json"}});if(!r.ok)throw new Error(`PTD_SCHEMA_${r.status}`);return jp(await r.text());}
function vals(n){const o=[];(function w(v,d){if(!v||typeof v!=="object"||d>12)return;if(Array.isArray(v)){v.forEach(x=>w(x,d+1));return}if(Array.isArray(v.enum))o.push(...v.enum.map(String));if(v.const!==undefined)o.push(String(v.const));for(const k of["items","properties","oneOf","anyOf","allOf"])w(v[k],d+1)})(n,0);return[...new Set(o)];}
function measure(rows,key){return Array.isArray(rows)&&rows[0]&&Array.isArray(rows[0]?.[key])&&rows[0][key][0]?rows[0][key][0]:null;}
function gb(x){if(!x)return null;const n=Number(x.value),u=String(x.unit||"GB").toUpperCase();return!Number.isFinite(n)?null:u==="TB"?n*1024:u==="MB"?n/1024:n;}
function setStorage(rows,key,target){const x=clone(rows||[]),m=key==="hard_disk"?x?.[0]?.size?.[0]:x?.[0]?.installed_size?.[0];if(!m)throw new Error(`${key}_SHAPE`);m.value=target===1024?1:target;m.unit=target===1024?"TB":"GB";return x;}
function replace512(v,to){if(typeof v==="string")return v.split("512GB").join(to);if(Array.isArray(v))return v.map(x=>replace512(x,to));if(v&&typeof v==="object"){const o={};for(const[k,x]of Object.entries(v))o[k]=replace512(x,to);return o}return v;}
function ids(a){return(Array.isArray(a?.externally_assigned_product_identifier)?a.externally_assigned_product_identifier:[]).map(x=>String(x?.value||"").trim()).filter(Boolean)}
function build(src,target,ean,title,cell,type){const a=clone(src);for(const k of["externally_assigned_product_identifier","merchant_suggested_asin","supplier_declared_has_product_identifier_exemption","purchasable_offer","fulfillment_availability","list_price","minimum_seller_allowed_price","maximum_seller_allowed_price","merchant_shipping_group","parentage_level","child_parent_sku_relationship","variation_theme"])delete a[k];for(const k of Object.keys(a))if(/main_product_image_locator|other_product_image_locator|swatch_product_image_locator/i.test(k))delete a[k];a.hard_disk=setStorage(a.hard_disk,"hard_disk",target);a.flash_memory=setStorage(a.flash_memory,"flash_memory",target);for(const k of["item_name","bullet_point","product_description","generic_keyword","size"])if(a[k])a[k]=replace512(a[k],target===1024?"1TB":"256GB");if(a.item_name?.[0])a.item_name[0].value=title;a.externally_assigned_product_identifier=[{marketplace_id:MP,type:"ean",value:ean}];a.is_exclusive_product=[{marketplace_id:MP,value:false}];a.skip_offer=[{marketplace_id:MP,value:true}];a.batteries_required=[{marketplace_id:MP,value:true}];a.batteries_included=[{marketplace_id:MP,value:true}];a.battery=[{marketplace_id:MP,cell_composition:[{value:cell}]}];a.num_batteries=[{marketplace_id:MP,quantity:1,type}];a.has_multiple_battery_powered_components=[{marketplace_id:MP,value:false}];a.item_package_dimensions=[{marketplace_id:MP,length:{value:38.5,unit:"centimeters"},width:{value:27.5,unit:"centimeters"},height:{value:14,unit:"centimeters"}}];a.item_package_weight=[{marketplace_id:MP,value:1.9,unit:"kilograms"}];return a;}
function clean(a){const s=JSON.stringify(a);for(const t of["TOSHIBA","東芝","B0FN3KQFR3","B0FPC4R7ZG","F7-AF7O-IGX5","9K-D0RA-4R8V"])if(new RegExp(t,"i").test(s))return false;return true;}
async function putPreview(a,sku,attrs){const {sellerId,marketplaceId,endpoint}=cfg();const q=new URLSearchParams({marketplaceIds:marketplaceId,issueLocale:"ja_JP",includedData:"issues",mode:"VALIDATION_PREVIEW"});return req(`${endpoint}/listings/2021-08-01/items/${encodeURIComponent(sellerId)}/${encodeURIComponent(sku)}?${q}`,a,{method:"PUT",body:{productType:PT,requirements:"LISTING",attributes:attrs}});}
function sum(r){const issues=Array.isArray(r?.body?.issues)?r.body.issues:[],errors=issues.filter(i=>String(i?.severity||"").toUpperCase()==="ERROR"),status=String(r?.body?.status||"").toUpperCase();return{httpStatus:r.http,status,errorCount:errors.length,errors:errors.map(i=>({code:String(i.code||""),message:String(i.message||"").slice(0,500),attributeNames:i.attributeNames||[]})),valid:r.ok&&errors.length===0&&["VALID","ACCEPTED"].includes(status)};}
async function run(){const a=await token(),src=await listing(a,SOURCE_SKU);if(!src.ok)throw new Error(`SOURCE_${src.http}`);const sm=src.body?.summaries?.[0]||{},at=src.body?.attributes||{};if(String(sm.asin||"")!==SOURCE_ASIN||gb(measure(at?.ram_memory,"installed_size"))!==8||gb(measure(at?.hard_disk,"size"))!==512)throw new Error("SOURCE_DRIFT");for(const sku of[SKU256,SKU1TB]){const r=await listing(a,sku);if(r.ok)throw new Error(`NEW_SKU_EXISTS:${sku}`);if(r.http!==404)throw new Error(`NEW_SKU_PREFLIGHT_${sku}_${r.http}`)}for(const sku of FAMILY){const r=await listing(a,sku);if(r.ok){for(const id of ids(r.body?.attributes||{}))if(id===EAN256||id===EAN1TB)throw new Error(`EAN_REUSE:${id}`)}}const sc=await schema(a),batteryVals=vals(sc?.properties?.battery),numVals=vals(sc?.properties?.num_batteries),multiVals=vals(sc?.properties?.has_multiple_battery_powered_components),idVals=vals(sc?.properties?.externally_assigned_product_identifier);const cell=["lithium_polymer","lithium_ion"].find(x=>batteryVals.includes(x));const type=numVals.includes("nonstandard_battery")?"nonstandard_battery":null;const idType=idVals.find(x=>/^ean$/i.test(x))||"ean";if(!cell||!type||!multiVals.some(x=>/^false$/i.test(x)))return{status:"BLOCK_BATTERY_SCHEMA_UNRESOLVED",moduleVersion:VERSION,diagnostics:{batteryVals:batteryVals.filter(x=>/lithium/i.test(x)),numVals,multiVals,idVals},amazonPersistentWrites:0,externalChanges:0};const c256=build(at,256,EAN256,"【整備済み品】ダイナブック G83/HS 中古ノートパソコン 13.3型FHD 第11世代 Core i5-1135G7 メモリ8GB SSD256GB Windows 11 Pro MS Office 2024 Webカメラ Wi-Fi6 ノートン360付属 MTD整備済み",cell,type),c1=build(at,1024,EAN1TB,"【整備済み品】ダイナブック G83/HS 中古ノートパソコン 13.3型FHD 第11世代 Core i5-1135G7 メモリ8GB SSD1TB Windows 11 Pro MS Office 2024 Webカメラ Wi-Fi6 ノートン360付属 MTD整備済み",cell,type);if(!clean(c256)||!clean(c1))throw new Error("CLEAN_ROOM_BLOCK");c256.externally_assigned_product_identifier[0].type=idType;c1.externally_assigned_product_identifier[0].type=idType;const p256=sum(await putPreview(a,SKU256,c256)),p1=sum(await putPreview(a,SKU1TB,c1)),ready=p256.valid&&p1.valid;return{status:ready?"VALIDATION_PREVIEW_2_OF_2_PASS":"BLOCK",moduleVersion:VERSION,diagnostics:{cell,type,idType},preview:{ssd256:p256,ssd1tb:p1},readyForStandaloneLiveDesign:ready,liveAllowed:false,amazonPersistentWrites:0,inventoryWrites:0,priceWrites:0,yahooWrites:0,externalChanges:0};}
async function handler(req,res){try{const sec=String(process.env.AMAZON_STOCK_API_SECRET||"").trim();if(String(req.headers["x-api-secret"]||"")!==sec)return res.status(401).json({status:"BLOCK",error:"Unauthorized"});return res.status(200).json(await run())}catch(e){return res.status(400).json({status:"BLOCK",moduleVersion:VERSION,error:e?.message||String(e),amazonPersistentWrites:0,externalChanges:0})}}
express.application.listen=function(...args){if(!this?._router?.stack?.some(x=>x?.route?.path===ROUTE))this.post(ROUTE,handler);return oldListen.apply(this,args)};
