import express from "express";
import fetch from "node-fetch";
import "dotenv/config";
const VERSION="2026-09-09-g83-replacement-battery-diag-v1.0.0";
const MP="A1VC38T7YXB528",PT="NOTEBOOK_COMPUTER";
const SKUS=["F7-AF7O-IGX5","SO-9QJ3-7SHR","9K-D0RA-4R8V","E7-YLJ3-F9CY","5K-G098-FO9O","QH-ITJ6-BTTC"];
const oldListen=express.application.listen;
const jp=t=>{try{return t?JSON.parse(t):{};}catch{return{rawText:String(t||"").slice(0,5000)}}};
async function ft(url,opt={}){const c=new AbortController(),tm=setTimeout(()=>c.abort(),25000);try{return await fetch(url,{...opt,signal:c.signal})}finally{clearTimeout(tm)}}
async function token(){const r=await ft("https://api.amazon.com/auth/o2/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({grant_type:"refresh_token",refresh_token:process.env.REFRESH_TOKEN,client_id:process.env.LWA_CLIENT_ID,client_secret:process.env.LWA_CLIENT_SECRET})});const x=jp(await r.text());if(!r.ok||!x.access_token)throw new Error(`LWA_${r.status}`);return x.access_token;}
function cfg(){const sellerId=String(process.env.SPAPI_SELLER_ID||"").trim(),marketplaceId=String(process.env.SPAPI_MARKETPLACE_ID||MP).trim(),endpoint=String(process.env.SPAPI_ENDPOINT||"https://sellingpartnerapi-fe.amazon.com").replace(/\/$/,"");return{sellerId,marketplaceId,endpoint};}
async function req(url,a){const r=await ft(url,{headers:{"x-amz-access-token":a,accept:"application/json"}});return{http:r.status,ok:r.ok,body:jp(await r.text())};}
async function listing(a,sku){const {sellerId,marketplaceId,endpoint}=cfg();const q=new URLSearchParams({marketplaceIds:marketplaceId,includedData:"summaries,attributes,issues",issueLocale:"ja_JP"});return req(`${endpoint}/listings/2021-08-01/items/${encodeURIComponent(sellerId)}/${encodeURIComponent(sku)}?${q}`,a);}
async function schema(a){const {sellerId,marketplaceId,endpoint}=cfg();const q=new URLSearchParams({sellerId,marketplaceIds:marketplaceId,requirements:"LISTING",requirementsEnforced:"ENFORCED",locale:"ja_JP"});const d=await req(`${endpoint}/definitions/2020-09-01/productTypes/${PT}?${q}`,a);const u=String(d.body?.schema?.link?.resource||"");const r=await ft(u,{headers:{accept:"application/json"}});return jp(await r.text());}
function compactSpec(spec){const out={};(function w(v,path,d){if(!v||typeof v!=="object"||d>8)return;if(Array.isArray(v.required)&&v.required.length)out[path+".__required"]=v.required;if(Array.isArray(v.enum)&&v.enum.length)out[path+".__enum"]=v.enum;if(v.const!==undefined)out[path+".__const"]=[v.const];if(v.type)out[path+".__type"]=v.type;if(v.properties)for(const[k,x]of Object.entries(v.properties))w(x,path?`${path}.${k}`:k,d+1);if(v.items)w(v.items,`${path}[]`,d+1);for(const k of["oneOf","anyOf","allOf"])if(Array.isArray(v[k]))v[k].forEach((x,i)=>w(x,`${path}.${k}[${i}]`,d+1));})(spec,"",0);return out;}
express.application.listen=function(...args){const server=oldListen.apply(this,args);setTimeout(async()=>{try{const a=await token(),rows=[];for(const sku of SKUS){const r=await listing(a,sku),at=r.body?.attributes||{};rows.push({sku,asin:r.body?.summaries?.[0]?.asin||null,battery:at.battery||null,lithium_battery:at.lithium_battery||null,contains_battery_or_cell:at.contains_battery_or_cell||null,number_of_lithium_ion_cells:at.number_of_lithium_ion_cells||null,num_batteries:at.num_batteries||null,batteries_required:at.batteries_required||null,batteries_included:at.batteries_included||null,has_multiple_battery_powered_components:at.has_multiple_battery_powered_components||null});}const sc=await schema(a),specs={battery:compactSpec(sc?.properties?.battery),lithium_battery:compactSpec(sc?.properties?.lithium_battery),contains_battery_or_cell:compactSpec(sc?.properties?.contains_battery_or_cell),number_of_lithium_ion_cells:compactSpec(sc?.properties?.number_of_lithium_ion_cells)};console.log(`G83_REPLACEMENT_BATTERY_DIAG=${JSON.stringify({version:VERSION,rows,specs,amazonPersistentWrites:0,externalChanges:0})}`)}catch(e){console.error(`G83_REPLACEMENT_BATTERY_DIAG_ERROR=${JSON.stringify({version:VERSION,error:e?.message||String(e)})}`)}},3500);return server};
