import express from "express";
import fetch from "node-fetch";
import crypto from "node:crypto";
import "dotenv/config";

const MODULE_VERSION="2026-09-13-g83-hs-six-b2c-price-live-v2.1.0";
const ROUTE="/amazon/price/g83-replacement/b2c-validation-preview";
const TOKEN="G83_HS_B2C_PRICE_6_PREVIEW_20260913_V2";
const LIVE_ROUTE="/amazon/price/g83-hs/b2c-live-approved";
const LIVE_TOKEN="G83_HS_B2C_PRICE_6_LIVE_APPROVED_20260913";
const AUDIT_ROUTE="/amazon/price/g83-hs/b2c-live-audit";
const AUDIT_TOKEN="G83_HS_B2C_PRICE_6_AUDIT_20260913_V1";
const MARKETPLACE="A1VC38T7YXB528";
const originalListen=express.application.listen;
const TARGETS=Object.freeze([
 {sku:"g83-hs-i5-11g-8gb-ssd256-r1",asin:"B0HJ8L6KJY",price:35800,min:25200,currentPrice:null,currentMin:null,points:null},
 {sku:"SO-9QJ3-7SHR",asin:"B0FPC2JKBY",price:45800,min:40100,currentPrice:77000,currentMin:39400,points:770},
 {sku:"g83-hs-i5-11g-8gb-ssd1tb-r1",asin:"B0HJ8SKQGG",price:55800,min:54100,currentPrice:null,currentMin:null,points:null},
 {sku:"E7-YLJ3-F9CY",asin:"B0GZBHBQN2",price:43800,min:36700,currentPrice:43800,currentMin:36200,points:438},
 {sku:"5K-G098-FO9O",asin:"B0FPC52B8K",price:53800,min:51500,currentPrice:78000,currentMin:50800,points:780},
 {sku:"QH-ITJ6-BTTC",asin:"B0FPC385LM",price:66800,min:65900,currentPrice:87000,currentMin:65200,points:870}
]);
const parse=t=>{try{return t?JSON.parse(t):{};}catch{return{rawText:String(t||"").slice(0,1200)}}};
const clone=v=>JSON.parse(JSON.stringify(v));
const audience=o=>String(o?.audience||"ALL").toUpperCase();
const offerType=o=>String(o?.offerType||o?.offer_type||"").toUpperCase();
const hash=v=>crypto.createHash("sha256").update(JSON.stringify(v)).digest("hex");
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function num(v){if(v===null||v===undefined||v==="")return null;if(typeof v==="object"){for(const k of ["pointsNumber","PointsNumber","points_number","amount","Amount","value","Value"]){const n=num(v?.[k]);if(n!==null)return n;}return null;}const n=Number(v);return Number.isFinite(n)?n:null;}
function cfg(){const sellerId=String(process.env.SPAPI_SELLER_ID||"").trim();if(!sellerId)throw new Error("Missing SPAPI_SELLER_ID");return{sellerId,marketplaceId:String(process.env.SPAPI_MARKETPLACE_ID||MARKETPLACE).trim(),endpoint:String(process.env.SPAPI_ENDPOINT||"https://sellingpartnerapi-fe.amazon.com").replace(/\/$/,"")};}
async function lwa(){const{LWA_CLIENT_ID:client_id,LWA_CLIENT_SECRET:client_secret,REFRESH_TOKEN:refresh_token}=process.env;if(!client_id||!client_secret||!refresh_token)throw new Error("Missing LWA env");const r=await fetch("https://api.amazon.com/auth/o2/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({grant_type:"refresh_token",refresh_token,client_id,client_secret})});const j=parse(await r.text());if(!r.ok||!j.access_token)throw new Error(`LWA ${r.status}`);return j.access_token;}
async function request(url,opt){const r=await fetch(url,opt);const j=parse(await r.text());if(!r.ok)throw new Error(`SPAPI ${r.status} ${JSON.stringify(j).slice(0,1800)}`);return{r,j};}
async function getListing(a,sku){const{sellerId,marketplaceId,endpoint}=cfg();const q=new URLSearchParams({marketplaceIds:marketplaceId,includedData:"summaries,attributes,issues,offers,fulfillmentAvailability",issueLocale:"ja_JP"});return(await request(`${endpoint}/listings/2021-08-01/items/${encodeURIComponent(sellerId)}/${encodeURIComponent(sku)}?${q}`,{headers:{"x-amz-access-token":a,accept:"application/json"}})).j;}
function val(o,k){return num(o?.[k]?.[0]?.schedule?.[0]?.value_with_tax);}
function actualPoints(listing){const offers=Array.isArray(listing?.offers)?listing.offers:[];const b2c=offers.find(o=>offerType(o)==="B2C"||audience(o)==="ALL")||null;return b2c&&Object.prototype.hasOwnProperty.call(b2c,"points")?num(b2c.points):null;}
function setValue(offer,key,value){if(Array.isArray(offer?.[key])&&offer[key][0]&&Array.isArray(offer[key][0].schedule)&&offer[key][0].schedule[0])offer[key][0].schedule[0].value_with_tax=value;else offer[key]=[{schedule:[{value_with_tax:value}]}];}
function makeConsumer(t,m){return{currency:"JPY",audience:"ALL",our_price:[{schedule:[{value_with_tax:t.price}]}],minimum_seller_allowed_price:[{schedule:[{value_with_tax:t.min}]}],marketplace_id:m};}
function protectedConsumer(o){if(!o)return null;const x=clone(o);delete x.our_price;delete x.minimum_seller_allowed_price;return x;}
function inspectExpected(t,listing){const s=Array.isArray(listing?.summaries)?listing.summaries[0]||{}:{};if(String(s.asin||"")!==t.asin)throw new Error(`ASIN_MISMATCH ${t.sku}`);const before=clone(Array.isArray(listing?.attributes?.purchasable_offer)?listing.attributes.purchasable_offer:[]);const c0=before.find(x=>audience(x)!=="B2B")||null;const p0=actualPoints(listing);const cp=val(c0,"our_price"),cm=val(c0,"minimum_seller_allowed_price");if(cp!==t.currentPrice)throw new Error(`CURRENT_PRICE_MISMATCH ${t.sku} expected=${t.currentPrice} actual=${cp}`);if(cm!==t.currentMin)throw new Error(`CURRENT_MIN_MISMATCH ${t.sku} expected=${t.currentMin} actual=${cm}`);if(p0!==t.points)throw new Error(`POINTS_MISMATCH ${t.sku} expected=${t.points} actual=${p0}`);return prepare(t,listing,before,c0,p0,s);}
function prepare(t,listing,before,c0,p0,s){const{marketplaceId}=cfg();const beforeB2B=before.filter(x=>audience(x)==="B2B");const beforeProtected=protectedConsumer(c0);const after=clone(before);let i=after.findIndex(x=>audience(x)!=="B2B");if(i<0){after.push(makeConsumer(t,marketplaceId));i=after.length-1;}else{const protectedBefore=JSON.stringify(protectedConsumer(after[i]));after[i].currency=after[i].currency||"JPY";after[i].audience=after[i].audience||"ALL";after[i].marketplace_id=after[i].marketplace_id||marketplaceId;setValue(after[i],"our_price",t.price);setValue(after[i],"minimum_seller_allowed_price",t.min);if(JSON.stringify(protectedConsumer(after[i]))!==protectedBefore)throw new Error(`CONSUMER_PROTECTED_MUTATION ${t.sku}`);}if(JSON.stringify(beforeB2B)!==JSON.stringify(after.filter(x=>audience(x)==="B2B")))throw new Error(`B2B_MUTATION ${t.sku}`);return{t,s,before,c0,p0,after,beforeB2B,beforeB2BHash:hash(beforeB2B),beforeProtected,beforeProtectedHash:hash(beforeProtected),beforeMax:val(c0,"maximum_seller_allowed_price"),hadConsumer:Boolean(c0),listingErrorCount:(Array.isArray(listing?.issues)?listing.issues:[]).filter(x=>String(x?.severity||"").toUpperCase()==="ERROR").length};}
async function patchPlan(a,plan,mode){const{sellerId,marketplaceId,endpoint}=cfg();const q=new URLSearchParams({marketplaceIds:marketplaceId,issueLocale:"ja_JP"});if(mode)q.set("mode",mode);const body={productType:String(plan.s.productType||"NOTEBOOK_COMPUTER"),patches:[{op:"replace",path:"/attributes/purchasable_offer",value:plan.after}]};const{r,j}=await request(`${endpoint}/listings/2021-08-01/items/${encodeURIComponent(sellerId)}/${encodeURIComponent(plan.t.sku)}?${q}`,{method:"PATCH",headers:{"x-amz-access-token":a,accept:"application/json","content-type":"application/json"},body:JSON.stringify(body)});const issues=Array.isArray(j?.issues)?j.issues:[];const errors=issues.filter(x=>String(x?.severity||"").toUpperCase()==="ERROR");return{httpStatus:r.status,responseStatus:String(j?.status||""),submissionId:String(j?.submissionId||""),issueCodes:issues.map(x=>String(x?.code||"")).filter(Boolean),passed:r.ok&&errors.length===0};}
function auth(req){const sec=String(process.env.AMAZON_STOCK_API_SECRET||"").trim();if(!sec)throw new Error("secret missing");if(String(req.headers["x-api-secret"]||"")!==sec)throw new Error("Unauthorized");}
function matrixChecks(){return{storageMonotonic8gb:TARGETS[0].price<TARGETS[1].price&&TARGETS[1].price<TARGETS[2].price,storageMonotonic16gb:TARGETS[3].price<TARGETS[4].price&&TARGETS[4].price<TARGETS[5].price,ramPremium256:TARGETS[3].price>TARGETS[0].price,ramPremium512:TARGETS[4].price>TARGETS[1].price,ramPremium1tb:TARGETS[5].price>TARGETS[2].price};}
async function previewHandler(req,res){try{auth(req);if(String(req.body?.batchToken||"")!==TOKEN)throw new Error("GUARD_BLOCKED invalid batchToken");if(req.body?.dryRun===false)throw new Error("LIVE_DISABLED validation preview only");const a=await lwa();const results=[];for(const t of TARGETS){const plan=inspectExpected(t,await getListing(a,t.sku));const x=await patchPlan(a,plan,"VALIDATION_PREVIEW");results.push({sku:t.sku,asin:t.asin,currentPrice:t.currentPrice,currentMin:t.currentMin,currentPoints:plan.p0,targetPrice:t.price,targetMin:t.min,statuses:Array.isArray(plan.s.status)?plan.s.status:[],listingErrorCount:plan.listingErrorCount,b2bPreserved:true,consumerProtectedFieldsPreserved:true,pointsPathNotPatched:true,httpStatus:x.httpStatus,responseStatus:x.responseStatus,submissionId:x.submissionId,previewIssueCodes:x.issueCodes,validationPassed:x.passed,externalChanges:0});}const passed=results.filter(x=>x.validationPassed).length;return res.status(200).json({ok:passed===TARGETS.length,moduleVersion:MODULE_VERSION,route:ROUTE,batchToken:TOKEN,decision:passed===TARGETS.length?"G83_HS_B2C_PRICE_PREVIEW_ALL_6_PASS":"G83_HS_B2C_PRICE_PREVIEW_HAS_ERRORS",previewCalls:results.length,validationPassedCount:passed,validationFailedCount:results.length-passed,safety:{mode:"VALIDATION_PREVIEW",persistentAmazonWrites:0,liveCalls:0,externalChanges:0},matrixChecks:matrixChecks(),results,externalChanges:0});}catch(e){return res.status(409).json({ok:false,moduleVersion:MODULE_VERSION,route:ROUTE,decision:"STOP_FAIL_CLOSED",safety:{persistentAmazonWrites:0,liveCalls:0,externalChanges:0},externalChanges:0,error:e?.message||String(e)});}}
async function liveHandler(req,res){let liveCalls=0;const mutationResults=[];try{auth(req);if(String(req.body?.confirm||"")!==LIVE_TOKEN)throw new Error("LIVE_CONFIRM_REQUIRED");if(req.body?.live!==true)throw new Error("LIVE_FLAG_REQUIRED");const mc=matrixChecks();if(Object.values(mc).some(v=>v!==true))throw new Error("MATRIX_CHECK_FAILED");const a=await lwa();const firstPlans=[];for(const t of TARGETS)firstPlans.push(inspectExpected(t,await getListing(a,t.sku)));const previews=[];for(const p of firstPlans){const x=await patchPlan(a,p,"VALIDATION_PREVIEW");previews.push({sku:p.t.sku,...x});if(!x.passed)throw new Error(`FINAL_PREVIEW_FAILED ${p.t.sku}`);}const secondPlans=[];for(let i=0;i<TARGETS.length;i++){const p=inspectExpected(TARGETS[i],await getListing(a,TARGETS[i].sku));const f=firstPlans[i];if(p.beforeB2BHash!==f.beforeB2BHash)throw new Error(`B2B_CHANGED_DURING_PREFLIGHT ${p.t.sku}`);if(p.beforeProtectedHash!==f.beforeProtectedHash)throw new Error(`CONSUMER_PROTECTED_CHANGED_DURING_PREFLIGHT ${p.t.sku}`);if(p.beforeMax!==f.beforeMax)throw new Error(`MAX_CHANGED_DURING_PREFLIGHT ${p.t.sku}`);secondPlans.push(p);}for(const p of secondPlans){const x=await patchPlan(a,p,null);liveCalls++;mutationResults.push({sku:p.t.sku,asin:p.t.asin,targetPrice:p.t.price,targetMin:p.t.min,beforePrice:p.t.currentPrice,beforeMin:p.t.currentMin,beforePoints:p.p0,beforeMax:p.beforeMax,hadConsumer:p.hadConsumer,beforeB2BHash:p.beforeB2BHash,beforeProtectedHash:p.beforeProtectedHash,httpStatus:x.httpStatus,responseStatus:x.responseStatus,submissionId:x.submissionId,issueCodes:x.issueCodes,accepted:x.passed});if(!x.passed)throw new Error(`LIVE_PATCH_FAILED ${p.t.sku}`);}return res.status(200).json({ok:true,moduleVersion:MODULE_VERSION,route:LIVE_ROUTE,decision:"G83_HS_B2C_PRICE_6_LIVE_SUBMITTED",confirm:LIVE_TOKEN,finalPreviewCalls:previews.length,liveCalls,persistentAmazonWrites:liveCalls,externalChanges:liveCalls,matrixChecks:mc,previews,results:mutationResults});}catch(e){return res.status(liveCalls?500:409).json({ok:false,moduleVersion:MODULE_VERSION,route:LIVE_ROUTE,decision:liveCalls?"LIVE_PARTIAL_STOP":"LIVE_PREWRITE_STOP",liveCalls,persistentAmazonWrites:liveCalls,externalChanges:liveCalls,results:mutationResults,error:e?.message||String(e)});}}
async function auditHandler(req,res){try{auth(req);if(String(req.body?.auditToken||"")!==AUDIT_TOKEN)throw new Error("AUDIT_TOKEN_REQUIRED");const expected=Array.isArray(req.body?.expected)?req.body.expected:[];const expectedBySku=new Map(expected.map(x=>[String(x?.sku||""),x]));const a=await lwa();const results=[];for(const t of TARGETS){const listing=await getListing(a,t.sku);const s=Array.isArray(listing?.summaries)?listing.summaries[0]||{}:{};if(String(s.asin||"")!==t.asin)throw new Error(`ASIN_MISMATCH ${t.sku}`);const offers=clone(Array.isArray(listing?.attributes?.purchasable_offer)?listing.attributes.purchasable_offer:[]);const c=offers.find(x=>audience(x)!=="B2B")||null;const b2b=offers.filter(x=>audience(x)==="B2B");const p=actualPoints(listing);const e=expectedBySku.get(t.sku)||{};const currentPrice=val(c,"our_price"),currentMin=val(c,"minimum_seller_allowed_price"),currentMax=val(c,"maximum_seller_allowed_price");const b2bHash=hash(b2b),protectedHash=hash(protectedConsumer(c));const issueCodes=(Array.isArray(listing?.issues)?listing.issues:[]).filter(x=>String(x?.severity||"").toUpperCase()==="ERROR").map(x=>String(x?.code||"")).filter(Boolean);const targetMatched=currentPrice===t.price&&currentMin===t.min;const pointsPreserved=p===(Object.prototype.hasOwnProperty.call(e,"points")?e.points:t.points);const maxPreserved=currentMax===(Object.prototype.hasOwnProperty.call(e,"max")?e.max:null);const b2bPreserved=!e.b2bHash||b2bHash===e.b2bHash;const protectedPreserved=e.hadConsumer===false?true:(!e.protectedHash||protectedHash===e.protectedHash);results.push({sku:t.sku,asin:t.asin,currentPrice,currentMin,currentPoints:p,currentMax,targetPrice:t.price,targetMin:t.min,statuses:Array.isArray(s.status)?s.status:[],issueCodes,listingErrorCount:issueCodes.length,b2bHash,protectedHash,targetMatched,pointsPreserved,maxPreserved,b2bPreserved,consumerProtectedFieldsPreserved:protectedPreserved,pass:targetMatched&&pointsPreserved&&maxPreserved&&b2bPreserved&&protectedPreserved&&issueCodes.length===0});}const passCount=results.filter(x=>x.pass).length;return res.status(200).json({ok:passCount===TARGETS.length,moduleVersion:MODULE_VERSION,route:AUDIT_ROUTE,decision:passCount===TARGETS.length?"G83_HS_B2C_PRICE_6_POSTLIVE_AUDIT_PASS":"G83_HS_B2C_PRICE_6_POSTLIVE_AUDIT_PENDING",passCount,total:TARGETS.length,persistentAmazonWrites:0,externalChanges:0,results});}catch(e){return res.status(409).json({ok:false,moduleVersion:MODULE_VERSION,route:AUDIT_ROUTE,decision:"AUDIT_STOP",persistentAmazonWrites:0,externalChanges:0,error:e?.message||String(e)});}}
express.application.listen=function g83HsSixB2CPriceLiveListen(...args){const stack=this?._router?.stack||[];if(!stack.some(l=>l?.route?.path===ROUTE))this.post(ROUTE,previewHandler);if(!stack.some(l=>l?.route?.path===LIVE_ROUTE))this.post(LIVE_ROUTE,liveHandler);if(!stack.some(l=>l?.route?.path===AUDIT_ROUTE))this.post(AUDIT_ROUTE,auditHandler);return originalListen.apply(this,args);};
