import express from "express";
import fetch from "node-fetch";
import "dotenv/config";
const VERSION="2026-09-09-g83-replacement-postcreate-audit-v1.0.0";
const MP="A1VC38T7YXB528",PARENT_SKU="g83-hs-i5-11g-variation-parent",PARENT_ASIN="B0HHYNVYD5";
const TARGETS=[{sku:"g83-hs-i5-11g-8gb-ssd256-r1",ean:"4595989934973",storageGB:256},{sku:"g83-hs-i5-11g-8gb-ssd1tb-r1",ean:"4595989934980",storageGB:1024}];
const CURRENT=["F7-AF7O-IGX5","SO-9QJ3-7SHR","9K-D0RA-4R8V","E7-YLJ3-F9CY","5K-G098-FO9O","QH-ITJ6-BTTC"];
const oldListen=express.application.listen,jp=t=>{try{return t?JSON.parse(t):{};}catch{return{rawText:String(t||"").slice(0,3000)}}};
function cfg(){return{sellerId:String(process.env.SPAPI_SELLER_ID||"").trim(),marketplaceId:String(process.env.SPAPI_MARKETPLACE_ID||MP).trim(),endpoint:String(process.env.SPAPI_ENDPOINT||"https://sellingpartnerapi-fe.amazon.com").replace(/\/$/,"")}}
async function ft(url,opt={}){const c=new AbortController(),tm=setTimeout(()=>c.abort(),25000);try{return await fetch(url,{...opt,signal:c.signal})}finally{clearTimeout(tm)}}
async function token(){const r=await ft("https://api.amazon.com/auth/o2/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({grant_type:"refresh_token",refresh_token:process.env.REFRESH_TOKEN,client_id:process.env.LWA_CLIENT_ID,client_secret:process.env.LWA_CLIENT_SECRET})});const x=jp(await r.text());if(!r.ok||!x.access_token)throw new Error(`LWA_${r.status}`);return x.access_token;}
async function req(url,a){const r=await ft(url,{headers:{"x-amz-access-token":a,accept:"application/json"}});return{http:r.status,ok:r.ok,body:jp(await r.text())};}
async function listing(a,sku){const {sellerId,marketplaceId,endpoint}=cfg();const q=new URLSearchParams({marketplaceIds:marketplaceId,includedData:"summaries,attributes,issues",issueLocale:"ja_JP"});return req(`${endpoint}/listings/2021-08-01/items/${encodeURIComponent(sellerId)}/${encodeURIComponent(sku)}?${q}`,a)}
async function catalog(a,asin){const {marketplaceId,endpoint}=cfg();const q=new URLSearchParams({marketplaceIds:marketplaceId,includedData:"summaries,relationships,productTypes,attributes"});return req(`${endpoint}/catalog/2022-04-01/items/${encodeURIComponent(asin)}?${q}`,a)}
async function searchEan(a,ean){const {marketplaceId,endpoint}=cfg();const q=new URLSearchParams({marketplaceIds:marketplaceId,identifiers:ean,identifiersType:"EAN",includedData:"summaries,relationships,productTypes,attributes"});return req(`${endpoint}/catalog/2022-04-01/items?${q}`,a)}
function first(a,k="value"){return Array.isArray(a)&&a[0]?a[0]?.[k]??null:null}
function nested(a,k){return Array.isArray(a)&&a[0]&&Array.isArray(a[0]?.[k])&&a[0][k][0]?a[0][k][0]?.value??null:null}
function snap(sku,r){if(!r.ok)return{sku,http:r.http,exists:false};const b=r.body||{},sm=b.summaries?.[0]||{},at=b.attributes||{},issues=Array.isArray(b.issues)?b.issues:[];return{sku,http:r.http,exists:true,asin:String(sm.asin||""),productType:String(sm.productType||""),title:String(sm.itemName||first(at.item_name)||""),ean:first(at.externally_assigned_product_identifier)||at.externally_assigned_product_identifier?.[0]?.value||null,ramGB:Number(nested(at.ram_memory,"installed_size")??NaN),storageGB:Number(nested(at.hard_disk,"size")??NaN),parentage:first(at.parentage_level),parentSku:first(at.child_parent_sku_relationship,"parent_sku"),theme:first(at.variation_theme,"name"),errorCount:issues.filter(i=>String(i?.severity||"").toUpperCase()==="ERROR").length,issues:issues.map(i=>({code:i.code,severity:i.severity,message:String(i.message||"").slice(0,300)}))}}
function relAsins(node){const out=[];(function w(v,d){if(v==null||d>10)return;if(typeof v==="string"&&/^[A-Z0-9]{10}$/.test(v))out.push(v);else if(Array.isArray(v))v.forEach(x=>w(x,d+1));else if(typeof v==="object")Object.values(v).forEach(x=>w(x,d+1))})(node,0);return[...new Set(out)]}
async function run(){const a=await token(),targets=[];for(const t of TARGETS){const lr=await listing(a,t.sku),ls=snap(t.sku,lr),sr=await searchEan(a,t.ean),items=Array.isArray(sr.body?.items)?sr.body.items:[];targets.push({...t,listing:ls,catalogSearch:{http:sr.http,ok:sr.ok,numberOfResults:Number(sr.body?.numberOfResults||items.length||0),items:items.map(x=>({asin:x.asin||"",productTypes:x.productTypes||[],summaries:x.summaries||[],relationshipAsins:relAsins(x.relationships||[])}))}})}const parentL=snap(PARENT_SKU,await listing(a,PARENT_SKU)),pc=await catalog(a,parentL.asin||PARENT_ASIN),current=[];for(const sku of CURRENT)current.push(snap(sku,await listing(a,sku)));return{status:"G83_REPLACEMENT_POSTCREATE_AUDIT",moduleVersion:VERSION,readOnly:true,targets,parent:{listing:parentL,catalog:{http:pc.http,ok:pc.ok,relationshipAsins:relAsins(pc.body?.relationships||[]),relationships:pc.body?.relationships||[]}},currentChildren:current,amazonPersistentWrites:0,inventoryWrites:0,priceWrites:0,yahooWrites:0,externalChanges:0}}
express.application.listen=function(...args){const server=oldListen.apply(this,args);setTimeout(async()=>{try{console.log(`G83_REPLACEMENT_POSTCREATE_AUDIT_RESULT=${JSON.stringify(await run())}`)}catch(e){console.error(`G83_REPLACEMENT_POSTCREATE_AUDIT_ERROR=${JSON.stringify({moduleVersion:VERSION,error:e?.message||String(e)})}`)}},90000);return server};
