import fetch from "node-fetch";
import crypto from "crypto";
import "dotenv/config";

const VERSION="2026-09-12-s73-six-child-validation-preview-v1.0.0";
const TAG="S73_SIX_CHILD_VALIDATION_PREVIEW_RESULT";
const ERR="S73_SIX_CHILD_VALIDATION_PREVIEW_ERROR";
const MP="A1VC38T7YXB528",PT="NOTEBOOK_COMPUTER";
const THEME="HARD_DISK_SIZE/RAM_MEMORY_INSTALLED_SIZE";
const PARENT_SKU="s73-hs-i5-11g-16gb-storage-parent",PARENT_ASIN="B0HJ265LZ6";
const SOURCE_SKU="s73-hs-i5-11g-16gb-ssd512",SOURCE_ASIN="B0HJ28YCP7";
const EXISTING=[
 {sku:"7X-725F-2ZML",asin:"B0HGDBYRS8",ram:16,storage:256},
 {sku:"s73-hs-i5-11g-16gb-ssd512",asin:"B0HJ28YCP7",ram:16,storage:512},
];
const TARGETS=[
 {sku:"s73-hs-i5-11g-8gb-ssd256",ean:"4595778187016",ram:8,storage:256},
 {sku:"s73-hs-i5-11g-8gb-ssd512",ean:"4595989934997",ram:8,storage:512},
 {sku:"s73-hs-i5-11g-8gb-ssd1tb",ean:"4595778187023",ram:8,storage:1024},
 {sku:"s73-hs-i5-11g-16gb-ssd1tb",ean:"4595778187030",ram:16,storage:1024},
];
const clone=v=>JSON.parse(JSON.stringify(v));
const jp=t=>{try{return t?JSON.parse(t):{};}catch{return{rawText:String(t||"").slice(0,3000)}}};
const sha=v=>crypto.createHash("sha256").update(JSON.stringify(v)).digest("hex");
function cfg(){const sellerId=String(process.env.SPAPI_SELLER_ID||"").trim(),marketplaceId=String(process.env.SPAPI_MARKETPLACE_ID||MP).trim(),endpoint=String(process.env.SPAPI_ENDPOINT||"https://sellingpartnerapi-fe.amazon.com").replace(/\/$/,"");if(!sellerId)throw new Error("SPAPI_SELLER_ID_MISSING");if(marketplaceId!==MP)throw new Error(`MARKETPLACE_MISMATCH:${marketplaceId}`);return{sellerId,marketplaceId,endpoint};}
async function ft(url,opt={}){const c=new AbortController(),tm=setTimeout(()=>c.abort(),30000);try{return await fetch(url,{...opt,signal:c.signal})}finally{clearTimeout(tm)}}
async function token(){const r=await ft("https://api.amazon.com/auth/o2/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({grant_type:"refresh_token",refresh_token:process.env.REFRESH_TOKEN,client_id:process.env.LWA_CLIENT_ID,client_secret:process.env.LWA_CLIENT_SECRET})});const x=jp(await r.text());if(!r.ok||!x.access_token)throw new Error(`LWA_${r.status}`);return x.access_token;}
async function req(url,a,opt={}){const r=await ft(url,{method:opt.method||"GET",headers:{"x-amz-access-token":a,accept:"application/json",...(opt.body?{"content-type":"application/json"}:{})},...(opt.body?{body:JSON.stringify(opt.body)}:{})});return{http:r.status,ok:r.ok,body:jp(await r.text())};}
async function listing(a,sku){const{sellerId,marketplaceId,endpoint}=cfg(),q=new URLSearchParams({marketplaceIds:marketplaceId,includedData:"summaries,attributes,issues",issueLocale:"ja_JP"});return req(`${endpoint}/listings/2021-08-01/items/${encodeURIComponent(sellerId)}/${encodeURIComponent(sku)}?${q}`,a);}
async function schema(a){const{sellerId,marketplaceId,endpoint}=cfg(),q=new URLSearchParams({sellerId,marketplaceIds:marketplaceId,requirements:"LISTING",requirementsEnforced:"ENFORCED",locale:"ja_JP"});const d=await req(`${endpoint}/definitions/2020-09-01/productTypes/${PT}?${q}`,a);if(!d.ok)throw new Error(`PTD_${d.http}`);const u=String(d.body?.schema?.link?.resource||"");if(!u)throw new Error("PTD_LINK_MISSING");const r=await ft(u,{headers:{accept:"application/json"}});if(!r.ok)throw new Error(`PTD_SCHEMA_${r.status}`);return jp(await r.text());}
function vals(n){const out=[];(function w(v,d){if(!v||typeof v!=="object"||d>12)return;if(Array.isArray(v)){v.forEach(x=>w(x,d+1));return}if(Array.isArray(v.enum))out.push(...v.enum);if(v.const!==undefined)out.push(v.const);if(v.properties)Object.values(v.properties).forEach(x=>w(x,d+1));if(v.items)w(v.items,d+1);for(const k of["oneOf","anyOf","allOf"])if(Array.isArray(v[k]))v[k].forEach(x=>w(x,d+1));})(n,0);return[...new Set(out.map(String))];}
function validGtin13(v){if(!/^\d{13}$/.test(v))return false;const d=[...v].map(Number);let s=0;for(let i=0;i<12;i++)s+=d[i]*(i%2===0?1:3);return((10-s%10)%10)===d[12];}
function measure(rows,key){return Array.isArray(rows)&&rows[0]&&Array.isArray(rows[0]?.[key])&&rows[0][key][0]?rows[0][key][0]:null;}
function gb(x){if(!x)return null;const n=Number(x.value),u=String(x.unit||"GB").toUpperCase();if(!Number.isFinite(n))return null;return u==="TB"?n*1024:u==="MB"?n/1024:n;}
function setStorage(rows,key,target){const x=clone(rows||[]),m=key==="hard_disk"?x?.[0]?.size?.[0]:x?.[0]?.installed_size?.[0];if(!m)throw new Error(`${key}_SHAPE`);m.value=target===1024?1:target;m.unit=target===1024?"TB":"GB";return x;}
function setRam(rows,target){const x=clone(rows||[]),m=x?.[0]?.installed_size?.[0];if(!m)throw new Error("ram_memory_SHAPE");m.value=target;m.unit="GB";return x;}
function replaceText(v,ram,storage){const sl=storage===1024?"1TB":`${storage}GB`;if(typeof v==="string")return v.replace(/16GB/g,`${ram}GB`).replace(/512GB/g,sl);if(Array.isArray(v))return v.map(x=>replaceText(x,ram,storage));if(v&&typeof v==="object"){const o={};for(const[k,x]of Object.entries(v))o[k]=replaceText(x,ram,storage);return o}return v;}
function title(t){return `【整備済み品】ダイナブック S73/HS 13.3型 i5-1135G7 ${t.ram}GB SSD${t.storage===1024?"1TB":`${t.storage}GB`} Win11 Pro ノートン・Office付`;}
function idType(sc){const v=vals(sc?.properties?.externally_assigned_product_identifier);return v.find(x=>/^ean$/i.test(x))||v.find(x=>/ean/i.test(x))||"ean";}
function relationRows(){return{parentage_level:[{marketplace_id:MP,value:"child"}],variation_theme:[{name:THEME}],child_parent_sku_relationship:[{marketplace_id:MP,child_relationship_type:"variation",parent_sku:PARENT_SKU}]};}
function stripImages(a){for(const k of Object.keys(a))if(/main_product_image_locator|other_product_image_locator|swatch_product_image_locator/i.test(k))delete a[k];}
function build(src,t,identifierType){const a=clone(src);for(const k of["externally_assigned_product_identifier","merchant_suggested_asin","supplier_declared_has_product_identifier_exemption","purchasable_offer","fulfillment_availability","list_price","minimum_seller_allowed_price","maximum_seller_allowed_price","merchant_shipping_group","parentage_level","child_parent_sku_relationship","variation_theme"])delete a[k];stripImages(a);a.ram_memory=setRam(a.ram_memory,t.ram);a.hard_disk=setStorage(a.hard_disk,"hard_disk",t.storage);a.flash_memory=setStorage(a.flash_memory,"flash_memory",t.storage);for(const k of["item_name","bullet_point","product_description","generic_keyword","size"])if(a[k])a[k]=replaceText(a[k],t.ram,t.storage);if(a.item_name?.[0])a.item_name[0].value=title(t);a.externally_assigned_product_identifier=[{marketplace_id:MP,type:identifierType,value:t.ean}];a.is_exclusive_product=[{marketplace_id:MP,value:false}];Object.assign(a,relationRows());return a;}
async function putPreview(a,sku,attrs){const{sellerId,marketplaceId,endpoint}=cfg(),q=new URLSearchParams({marketplaceIds:marketplaceId,issueLocale:"ja_JP",includedData:"issues",mode:"VALIDATION_PREVIEW"}),body={productType:PT,requirements:"LISTING",attributes:attrs};const r=await req(`${endpoint}/listings/2021-08-01/items/${encodeURIComponent(sellerId)}/${encodeURIComponent(sku)}?${q}`,a,{method:"PUT",body});return{r,body};}
async function patchPreview(a,sku,patches){const{sellerId,marketplaceId,endpoint}=cfg(),q=new URLSearchParams({marketplaceIds:marketplaceId,issueLocale:"ja_JP",includedData:"issues",mode:"VALIDATION_PREVIEW"}),body={productType:PT,patches};const r=await req(`${endpoint}/listings/2021-08-01/items/${encodeURIComponent(sellerId)}/${encodeURIComponent(sku)}?${q}`,a,{method:"PATCH",body});return{r,body};}
function summary(x){const issues=Array.isArray(x?.r?.body?.issues)?x.r.body.issues:[],errors=issues.filter(i=>String(i?.severity||"").toUpperCase()==="ERROR"),status=String(x?.r?.body?.status||"").toUpperCase();return{httpStatus:x.r.http,status,submissionId:String(x.r.body?.submissionId||""),issueCount:issues.length,errorCount:errors.length,issues,valid:x.r.ok&&errors.length===0&&["VALID","ACCEPTED"].includes(status),payloadSha256:sha(x.body)};}
function clean(attrs,t){const s=JSON.stringify(attrs);const forbidden=["TOSHIBA","東芝","B0FN3KQFR3","B0FPC4R7ZG","F7-AF7O-IGX5","9K-D0RA-4R8V"];return{pass:!forbidden.some(x=>new RegExp(x,"i").test(s)),forbiddenHits:forbidden.filter(x=>new RegExp(x,"i").test(s)),eanPresent:s.includes(t.ean)};}
async function run(){for(const t of TARGETS)if(!validGtin13(t.ean))throw new Error(`GTIN_INVALID:${t.sku}:${t.ean}`);const a=await token(),sc=await schema(a),identifierType=idType(sc);if(!vals(sc?.properties?.variation_theme).includes(THEME))throw new Error("COMBINED_THEME_NOT_SUPPORTED");const src=await listing(a,SOURCE_SKU);if(!src.ok)throw new Error(`SOURCE_${src.http}`);const sm=src.body?.summaries?.[0]||{},sa=src.body?.attributes||{},si=Array.isArray(src.body?.issues)?src.body.issues:[];if(String(sm.asin||"")!==SOURCE_ASIN||String(sm.productType||"")!==PT||gb(measure(sa.ram_memory,"installed_size"))!==16||gb(measure(sa.hard_disk,"size"))!==512||si.some(i=>String(i?.severity||"").toUpperCase()==="ERROR"))throw new Error("SOURCE_GUARD_BLOCK");
 const parent=await listing(a,PARENT_SKU);if(!parent.ok||String(parent.body?.summaries?.[0]?.asin||"")!==PARENT_ASIN)throw new Error("PARENT_GUARD_BLOCK");const pa=parent.body?.attributes||{};const parentPatches=[];for(const k of["ram_memory","computer_memory","memory_storage_capacity","hard_disk","flash_memory"])if(Array.isArray(pa[k])&&pa[k].length)parentPatches.push({op:"delete",path:`/attributes/${k}`,value:clone(pa[k])});parentPatches.push({op:"replace",path:"/attributes/variation_theme",value:[{name:THEME}]});const parentPreview=summary(await patchPreview(a,PARENT_SKU,parentPatches));
 const existingPreviews=[];for(const e of EXISTING){const g=await listing(a,e.sku);if(!g.ok||String(g.body?.summaries?.[0]?.asin||"")!==e.asin)throw new Error(`EXISTING_GUARD_BLOCK:${e.sku}`);const at=g.body?.attributes||{},issues=Array.isArray(g.body?.issues)?g.body.issues:[];if(gb(measure(at.ram_memory,"installed_size"))!==e.ram||gb(measure(at.hard_disk,"size"))!==e.storage||issues.some(i=>String(i?.severity||"").toUpperCase()==="ERROR"))throw new Error(`EXISTING_SPEC_OR_ISSUE_BLOCK:${e.sku}`);existingPreviews.push({sku:e.sku,...summary(await patchPreview(a,e.sku,[{op:"replace",path:"/attributes/variation_theme",value:[{name:THEME}]}]))});}
 const childPreviews=[];for(const t of TARGETS){const g=await listing(a,t.sku);if(g.ok)throw new Error(`TARGET_SKU_ALREADY_EXISTS:${t.sku}`);if(g.http!==404)throw new Error(`TARGET_PREFLIGHT_HTTP:${t.sku}:${g.http}`);const attrs=build(sa,t,identifierType),c=clean(attrs,t);if(!c.pass||!c.eanPresent)throw new Error(`CLEAN_OR_EAN_BLOCK:${t.sku}:${JSON.stringify(c)}`);const p=summary(await putPreview(a,t.sku,attrs));childPreviews.push({sku:t.sku,ean:t.ean,ramGB:t.ram,storageGB:t.storage,title:title(t),clean:c,...p});}
 const pass=parentPreview.valid&&existingPreviews.every(x=>x.valid)&&childPreviews.every(x=>x.valid);return{status:pass?"S73_SIX_VARIATION_VALIDATION_7_OF_7_PASS":"S73_SIX_VARIATION_VALIDATION_REVIEW_REQUIRED",moduleVersion:VERSION,identifierType,parentMigration:{sku:PARENT_SKU,asin:PARENT_ASIN,removedVariationSpecificKeys:parentPatches.filter(x=>x.op==="delete").map(x=>x.path),targetTheme:THEME,preview:parentPreview},existingChildThemeMigration:existingPreviews,newChildren:childPreviews,liveAllowed:false,liveBlockedReason:"EXPLICIT_USER_LIVE_APPROVAL_REQUIRED",amazonPersistentWrites:0,inventoryWrites:0,priceWrites:0,b2bWrites:0,adsWrites:0,yahooWrites:0,externalChanges:0};}
setTimeout(()=>run().then(x=>console.log(`${TAG}=${JSON.stringify(x)}`)).catch(e=>console.error(`${ERR}=${JSON.stringify({moduleVersion:VERSION,error:e?.message||String(e),amazonPersistentWrites:0,inventoryWrites:0,priceWrites:0,b2bWrites:0,adsWrites:0,yahooWrites:0,externalChanges:0})}`)),5000);
