import fetch from "node-fetch";
import crypto from "crypto";
import "dotenv/config";

const VERSION="2026-09-12-s73-six-child-live-v1.0.0";
const TAG="S73_SIX_CHILD_LIVE_RESULT";
const ERR="S73_SIX_CHILD_LIVE_ERROR";
const MP="A1VC38T7YXB528",PT="NOTEBOOK_COMPUTER";
const OLD_THEME="HARD_DISK_SIZE";
const THEME="HARD_DISK_SIZE/RAM_MEMORY_INSTALLED_SIZE";
const PARENT_SKU="s73-hs-i5-11g-16gb-storage-parent",PARENT_ASIN="B0HJ265LZ6";
const SOURCE_SKU="s73-hs-i5-11g-16gb-ssd512",SOURCE_ASIN="B0HJ28YCP7";
const APPROVAL="S73_6_CHILD_LIVE_APPROVED_20260912";
const EXISTING=[
 {sku:"7X-725F-2ZML",asin:"B0HGDBYRS8",ram:16,storage:256},
 {sku:"s73-hs-i5-11g-16gb-ssd512",asin:"B0HJ28YCP7",ram:16,storage:512},
];
const TARGETS=[
 {sku:"s73-hs-i5-11g-8gb-ssd256",ean:"4595778187016",ram:8,storage:256,previewSha:"68f48ecd81aaedf71f9c627b763e5d4e4c2ee4335b9c30c6c2e0f4e271309ba5"},
 {sku:"s73-hs-i5-11g-8gb-ssd512",ean:"4595989934997",ram:8,storage:512,previewSha:"1d50aeb3498bc2678bed0edd598ed945f2c07d026da3afd017054599a5f0589f"},
 {sku:"s73-hs-i5-11g-8gb-ssd1tb",ean:"4595778187023",ram:8,storage:1024,previewSha:"9467c64ea786fbefd24e174aab40c01e181d1d654cb6397d841f70dab7811556"},
 {sku:"s73-hs-i5-11g-16gb-ssd1tb",ean:"4595778187030",ram:16,storage:1024,previewSha:"3f48b85c376dfb5f4fa0a6477e73dc74449e7fd33957854ef47dcb7cae07a86b"},
];
const EXPECTED_PARENT_SHA="f42f508a32da83cb02de87b29cb9b958f5166e2dce07e8303df682dc904fbf2e";
const EXPECTED_EXISTING_SHA="555668185461e68729e9b484dd6d605a6faa5b31e0c50d78e0163f5577e0ae5e";
const clone=v=>JSON.parse(JSON.stringify(v));
const jp=t=>{try{return t?JSON.parse(t):{};}catch{return{rawText:String(t||"").slice(0,3000)}}};
const sha=v=>crypto.createHash("sha256").update(JSON.stringify(v)).digest("hex");
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function cfg(){const sellerId=String(process.env.SPAPI_SELLER_ID||"").trim(),marketplaceId=String(process.env.SPAPI_MARKETPLACE_ID||MP).trim(),endpoint=String(process.env.SPAPI_ENDPOINT||"https://sellingpartnerapi-fe.amazon.com").replace(/\/$/,"");if(!sellerId)throw new Error("SPAPI_SELLER_ID_MISSING");if(marketplaceId!==MP)throw new Error(`MARKETPLACE_MISMATCH:${marketplaceId}`);return{sellerId,marketplaceId,endpoint};}
async function ft(url,opt={}){const c=new AbortController(),tm=setTimeout(()=>c.abort(),30000);try{return await fetch(url,{...opt,signal:c.signal})}finally{clearTimeout(tm)}}
async function token(){const r=await ft("https://api.amazon.com/auth/o2/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({grant_type:"refresh_token",refresh_token:process.env.REFRESH_TOKEN,client_id:process.env.LWA_CLIENT_ID,client_secret:process.env.LWA_CLIENT_SECRET})});const x=jp(await r.text());if(!r.ok||!x.access_token)throw new Error(`LWA_${r.status}`);return x.access_token;}
async function req(url,a,opt={}){const r=await ft(url,{method:opt.method||"GET",headers:{"x-amz-access-token":a,accept:"application/json",...(opt.body?{"content-type":"application/json"}:{})},...(opt.body?{body:JSON.stringify(opt.body)}:{})});return{http:r.status,ok:r.ok,body:jp(await r.text())};}
async function listing(a,sku){const{sellerId,marketplaceId,endpoint}=cfg(),q=new URLSearchParams({marketplaceIds:marketplaceId,includedData:"summaries,attributes,issues",issueLocale:"ja_JP"});return req(`${endpoint}/listings/2021-08-01/items/${encodeURIComponent(sellerId)}/${encodeURIComponent(sku)}?${q}`,a);}
async function catalog(a,asin){const{marketplaceId,endpoint}=cfg(),q=new URLSearchParams({marketplaceIds:marketplaceId,includedData:"relationships,summaries"});return req(`${endpoint}/catalog/2022-04-01/items/${encodeURIComponent(asin)}?${q}`,a);}
async function schema(a){const{sellerId,marketplaceId,endpoint}=cfg(),q=new URLSearchParams({sellerId,marketplaceIds:marketplaceId,requirements:"LISTING",requirementsEnforced:"ENFORCED",locale:"ja_JP"});const d=await req(`${endpoint}/definitions/2020-09-01/productTypes/${PT}?${q}`,a);if(!d.ok)throw new Error(`PTD_${d.http}`);const u=String(d.body?.schema?.link?.resource||"");if(!u)throw new Error("PTD_LINK_MISSING");const r=await ft(u,{headers:{accept:"application/json"}});if(!r.ok)throw new Error(`PTD_SCHEMA_${r.status}`);return jp(await r.text());}
function vals(n){const out=[];(function w(v,d){if(!v||typeof v!=="object"||d>12)return;if(Array.isArray(v)){v.forEach(x=>w(x,d+1));return}if(Array.isArray(v.enum))out.push(...v.enum);if(v.const!==undefined)out.push(v.const);if(v.properties)Object.values(v.properties).forEach(x=>w(x,d+1));if(v.items)w(v.items,d+1);for(const k of["oneOf","anyOf","allOf"])if(Array.isArray(v[k]))v[k].forEach(x=>w(x,d+1));})(n,0);return[...new Set(out.map(String))];}
function validGtin13(v){if(!/^\d{13}$/.test(v))return false;const d=[...v].map(Number);let s=0;for(let i=0;i<12;i++)s+=d[i]*(i%2===0?1:3);return((10-s%10)%10)===d[12];}
function measure(rows,key){return Array.isArray(rows)&&rows[0]&&Array.isArray(rows[0]?.[key])&&rows[0][key][0]?rows[0][key][0]:null;}
function gb(x){if(!x)return null;const n=Number(x.value),u=String(x.unit||"GB").toUpperCase();if(!Number.isFinite(n))return null;return u==="TB"?n*1024:u==="MB"?n/1024:n;}
function ramGB(a){return gb(measure(a?.ram_memory,"installed_size"));}
function storageGB(a){return gb(measure(a?.hard_disk,"size"))??gb(measure(a?.flash_memory,"installed_size"));}
function setStorage(rows,key,target){const x=clone(rows||[]),m=key==="hard_disk"?x?.[0]?.size?.[0]:x?.[0]?.installed_size?.[0];if(!m)throw new Error(`${key}_SHAPE`);m.value=target===1024?1:target;m.unit=target===1024?"TB":"GB";return x;}
function setRam(rows,target){const x=clone(rows||[]),m=x?.[0]?.installed_size?.[0];if(!m)throw new Error("ram_memory_SHAPE");m.value=target;m.unit="GB";return x;}
function replaceText(v,ram,storage){const sl=storage===1024?"1TB":`${storage}GB`;if(typeof v==="string")return v.replace(/16GB/g,`${ram}GB`).replace(/512GB/g,sl);if(Array.isArray(v))return v.map(x=>replaceText(x,ram,storage));if(v&&typeof v==="object"){const o={};for(const[k,x]of Object.entries(v))o[k]=replaceText(x,ram,storage);return o}return v;}
function title(t){return `【整備済み品】ダイナブック S73/HS 13.3型 i5-1135G7 ${t.ram}GB SSD${t.storage===1024?"1TB":`${t.storage}GB`} Win11 Pro ノートン・Office付`;}
function idType(sc){const v=vals(sc?.properties?.externally_assigned_product_identifier);return v.find(x=>/^ean$/i.test(x))||v.find(x=>/ean/i.test(x))||"ean";}
function relationRows(){return{parentage_level:[{marketplace_id:MP,value:"child"}],variation_theme:[{name:THEME}],child_parent_sku_relationship:[{marketplace_id:MP,child_relationship_type:"variation",parent_sku:PARENT_SKU}]};}
function stripImages(a){for(const k of Object.keys(a))if(/main_product_image_locator|other_product_image_locator|swatch_product_image_locator/i.test(k))delete a[k];}
function build(src,t,identifierType){const a=clone(src);for(const k of["externally_assigned_product_identifier","merchant_suggested_asin","supplier_declared_has_product_identifier_exemption","purchasable_offer","fulfillment_availability","minimum_seller_allowed_price","maximum_seller_allowed_price","merchant_shipping_group","parentage_level","child_parent_sku_relationship","variation_theme"])delete a[k];stripImages(a);if(!Array.isArray(a.list_price)||!a.list_price.length)throw new Error("SOURCE_LIST_PRICE_MISSING");a.ram_memory=setRam(a.ram_memory,t.ram);a.hard_disk=setStorage(a.hard_disk,"hard_disk",t.storage);a.flash_memory=setStorage(a.flash_memory,"flash_memory",t.storage);for(const k of["item_name","bullet_point","product_description","generic_keyword","size"])if(a[k])a[k]=replaceText(a[k],t.ram,t.storage);if(a.item_name?.[0])a.item_name[0].value=title(t);a.externally_assigned_product_identifier=[{marketplace_id:MP,type:identifierType,value:t.ean}];a.is_exclusive_product=[{marketplace_id:MP,value:false}];Object.assign(a,relationRows());return a;}
function clean(attrs,t){const s=JSON.stringify(attrs);const forbidden=["TOSHIBA","東芝","B0FN3KQFR3","B0FPC4R7ZG","F7-AF7O-IGX5","9K-D0RA-4R8V"];return{pass:!forbidden.some(x=>new RegExp(x,"i").test(s)),forbiddenHits:forbidden.filter(x=>new RegExp(x,"i").test(s)),eanPresent:s.includes(t.ean)};}
function patchBody(patches){return{productType:PT,patches};}
function putBody(attrs){return{productType:PT,requirements:"LISTING",attributes:attrs};}
async function patchReq(a,sku,patches,preview=false){const{sellerId,marketplaceId,endpoint}=cfg(),q=new URLSearchParams({marketplaceIds:marketplaceId,issueLocale:"ja_JP",includedData:"issues"});if(preview)q.set("mode","VALIDATION_PREVIEW");const body=patchBody(patches),r=await req(`${endpoint}/listings/2021-08-01/items/${encodeURIComponent(sellerId)}/${encodeURIComponent(sku)}?${q}`,a,{method:"PATCH",body});return{r,body};}
async function putReq(a,sku,attrs,preview=false){const{sellerId,marketplaceId,endpoint}=cfg(),q=new URLSearchParams({marketplaceIds:marketplaceId,issueLocale:"ja_JP",includedData:"issues"});if(preview)q.set("mode","VALIDATION_PREVIEW");const body=putBody(attrs),r=await req(`${endpoint}/listings/2021-08-01/items/${encodeURIComponent(sellerId)}/${encodeURIComponent(sku)}?${q}`,a,{method:"PUT",body});return{r,body};}
function summary(x){const issues=Array.isArray(x?.r?.body?.issues)?x.r.body.issues:[],errors=issues.filter(i=>String(i?.severity||"").toUpperCase()==="ERROR"),status=String(x?.r?.body?.status||"").toUpperCase();return{httpStatus:x.r.http,status,submissionId:String(x.r.body?.submissionId||""),issueCount:issues.length,errorCount:errors.length,issues,accepted:x.r.ok&&errors.length===0&&["VALID","ACCEPTED"].includes(status),payloadSha256:sha(x.body)};}
function relation(a){return{parentage:String(a?.parentage_level?.[0]?.value||""),parentSku:String(a?.child_parent_sku_relationship?.[0]?.parent_sku||""),relationship:String(a?.child_parent_sku_relationship?.[0]?.child_relationship_type||""),theme:String(a?.variation_theme?.[0]?.name||"")};}
function errorCount(j){return (Array.isArray(j?.issues)?j.issues:[]).filter(i=>String(i?.severity||"").toUpperCase()==="ERROR").length;}
function catalogChildren(j){const out=[];for(const block of Array.isArray(j?.relationships)?j.relationships:[]){for(const r of Array.isArray(block?.relationships)?block.relationships:[]){if(String(r?.type||"").toUpperCase()==="VARIATION")out.push(...(Array.isArray(r?.childAsins)?r.childAsins.map(String):[]));}}return[...new Set(out)];}
async function freshAudit(a){const rows=[];const expected=[...EXISTING,...TARGETS];for(const x of expected){const g=await listing(a,x.sku);const sm=g.body?.summaries?.[0]||{},at=g.body?.attributes||{},rel=relation(at);rows.push({sku:x.sku,http:g.http,asin:String(sm.asin||""),productType:String(sm.productType||""),ramGB:ramGB(at),storageGB:storageGB(at),errorCount:errorCount(g.body),relation:rel});}const p=await listing(a,PARENT_SKU),ps=p.body?.summaries?.[0]||{},pa=p.body?.attributes||{},pr=relation(pa),pc=await catalog(a,PARENT_ASIN),children=catalogChildren(pc.body),newAsins=rows.filter(r=>TARGETS.some(t=>t.sku===r.sku)).map(r=>r.asin).filter(Boolean),allAsins=rows.map(r=>r.asin).filter(Boolean);const childPass=rows.every(r=>r.http===200&&r.asin&&r.productType===PT&&r.errorCount===0&&r.relation.parentage==="child"&&r.relation.parentSku===PARENT_SKU&&r.relation.relationship==="variation"&&r.relation.theme===THEME&&expected.some(x=>x.sku===r.sku&&x.ram===r.ramGB&&x.storage===r.storageGB));const parentPass=p.http===200&&String(ps.asin||"")===PARENT_ASIN&&String(ps.productType||"")===PT&&errorCount(p.body)===0&&pr.parentage==="parent"&&pr.theme===THEME&&!Array.isArray(pa.ram_memory);const catalogPass=pc.http===200&&children.length===6&&allAsins.length===6&&allAsins.every(x=>children.includes(x));return{parent:{http:p.http,asin:String(ps.asin||""),errorCount:errorCount(p.body),relation:pr,ramAttributePresent:Array.isArray(pa.ram_memory)},children:rows,parentCatalog:{http:pc.http,childAsins:children},newAsins,childPass,parentPass,catalogPass,pass:parentPass&&childPass&&catalogPass};}
async function run(){let writes=[];if(APPROVAL!=="S73_6_CHILD_LIVE_APPROVED_20260912")throw new Error("APPROVAL_TOKEN_MISMATCH");for(const t of TARGETS)if(!validGtin13(t.ean))throw new Error(`GTIN_INVALID:${t.sku}:${t.ean}`);const a=await token(),sc=await schema(a),identifierType=idType(sc);if(!vals(sc?.properties?.variation_theme).includes(THEME))throw new Error("COMBINED_THEME_NOT_SUPPORTED");
 const src=await listing(a,SOURCE_SKU);if(!src.ok)throw new Error(`SOURCE_${src.http}`);const sm=src.body?.summaries?.[0]||{},sa=src.body?.attributes||{},si=Array.isArray(src.body?.issues)?src.body.issues:[];if(String(sm.asin||"")!==SOURCE_ASIN||String(sm.productType||"")!==PT||ramGB(sa)!==16||storageGB(sa)!==512||si.some(i=>String(i?.severity||"").toUpperCase()==="ERROR"))throw new Error("SOURCE_GUARD_BLOCK");if(!Array.isArray(sa.list_price)||!sa.list_price.length)throw new Error("SOURCE_LIST_PRICE_MISSING");if(relation(sa).theme!==OLD_THEME)throw new Error(`SOURCE_THEME_DRIFT:${relation(sa).theme}`);
 const parent=await listing(a,PARENT_SKU);if(!parent.ok||String(parent.body?.summaries?.[0]?.asin||"")!==PARENT_ASIN)throw new Error("PARENT_GUARD_BLOCK");const pa=parent.body?.attributes||{};if(relation(pa).theme!==OLD_THEME||ramGB(pa)!==16)throw new Error(`PARENT_STATE_DRIFT:${relation(pa).theme}:${ramGB(pa)}`);const parentPatches=[];for(const k of["ram_memory","computer_memory","memory_storage_capacity","hard_disk","flash_memory"])if(Array.isArray(pa[k])&&pa[k].length)parentPatches.push({op:"delete",path:`/attributes/${k}`,value:clone(pa[k])});parentPatches.push({op:"replace",path:"/attributes/variation_theme",value:[{name:THEME}]});const parentBody=patchBody(parentPatches);if(sha(parentBody)!==EXPECTED_PARENT_SHA)throw new Error(`PARENT_HASH_DRIFT:${sha(parentBody)}`);
 const existingPayloads=[];for(const e of EXISTING){const g=await listing(a,e.sku);if(!g.ok||String(g.body?.summaries?.[0]?.asin||"")!==e.asin)throw new Error(`EXISTING_GUARD_BLOCK:${e.sku}`);const at=g.body?.attributes||{},issues=Array.isArray(g.body?.issues)?g.body.issues:[];if(ramGB(at)!==e.ram||storageGB(at)!==e.storage||issues.some(i=>String(i?.severity||"").toUpperCase()==="ERROR")||relation(at).theme!==OLD_THEME)throw new Error(`EXISTING_STATE_DRIFT:${e.sku}`);const patches=[{op:"replace",path:"/attributes/variation_theme",value:[{name:THEME}]}],body=patchBody(patches);if(sha(body)!==EXPECTED_EXISTING_SHA)throw new Error(`EXISTING_HASH_DRIFT:${e.sku}:${sha(body)}`);existingPayloads.push({e,patches,body});}
 const newPayloads=[];for(const t of TARGETS){const g=await listing(a,t.sku);if(g.ok)throw new Error(`TARGET_SKU_ALREADY_EXISTS:${t.sku}`);if(g.http!==404)throw new Error(`TARGET_PREFLIGHT_HTTP:${t.sku}:${g.http}`);const attrs=build(sa,t,identifierType),c=clean(attrs,t),body=putBody(attrs),h=sha(body);if(!c.pass||!c.eanPresent)throw new Error(`CLEAN_OR_EAN_BLOCK:${t.sku}:${JSON.stringify(c)}`);if(h!==t.previewSha)throw new Error(`TARGET_HASH_DRIFT:${t.sku}:${h}`);newPayloads.push({t,attrs,body});}
 const previews=[];let x=summary(await patchReq(a,PARENT_SKU,parentPatches,true));previews.push({type:"PARENT",sku:PARENT_SKU,...x});for(const z of existingPayloads){x=summary(await patchReq(a,z.e.sku,z.patches,true));previews.push({type:"EXISTING_CHILD",sku:z.e.sku,...x});}for(const z of newPayloads){x=summary(await putReq(a,z.t.sku,z.attrs,true));previews.push({type:"NEW_CHILD",sku:z.t.sku,...x});}if(!previews.every(v=>v.accepted))return{status:"S73_SIX_CHILD_LIVE_BLOCKED_AT_FRESH_PREVIEW",moduleVersion:VERSION,approval:APPROVAL,previews,writes,amazonPersistentWrites:0,inventoryWrites:0,priceWrites:0,b2bWrites:0,adsWrites:0,yahooWrites:0,externalChanges:0};
 const doWrite=async(type,sku,fn)=>{const r=summary(await fn());writes.push({type,sku,...r});return r.accepted;};
 if(!await doWrite("PATCH_PARENT_THEME_AND_REMOVE_RAM",PARENT_SKU,()=>patchReq(a,PARENT_SKU,parentPatches,false)))return{status:"S73_SIX_CHILD_LIVE_PARTIAL_STOP",moduleVersion:VERSION,writes,doNotRetryAutomatically:true,amazonPersistentWrites:writes.length,inventoryWrites:0,priceWrites:0,b2bWrites:0,adsWrites:0,yahooWrites:0,externalChanges:writes.length};
 for(const z of existingPayloads){if(!await doWrite("PATCH_EXISTING_CHILD_THEME",z.e.sku,()=>patchReq(a,z.e.sku,z.patches,false)))return{status:"S73_SIX_CHILD_LIVE_PARTIAL_STOP",moduleVersion:VERSION,writes,doNotRetryAutomatically:true,amazonPersistentWrites:writes.length,inventoryWrites:0,priceWrites:0,b2bWrites:0,adsWrites:0,yahooWrites:0,externalChanges:writes.length};}
 for(const z of newPayloads){if(!await doWrite("PUT_NEW_CHILD",z.t.sku,()=>putReq(a,z.t.sku,z.attrs,false)))return{status:"S73_SIX_CHILD_LIVE_PARTIAL_STOP",moduleVersion:VERSION,writes,doNotRetryAutomatically:true,amazonPersistentWrites:writes.length,inventoryWrites:0,priceWrites:0,b2bWrites:0,adsWrites:0,yahooWrites:0,externalChanges:writes.length};}
 let audit=null;for(let i=1;i<=18;i++){await sleep(i===1?5000:5000);audit=await freshAudit(a);audit.attempt=i;if(audit.pass)break;}
 return{status:audit?.pass?"S73_CATALOG_6_OF_6_PASS":"S73_LIVE_7_ACCEPTED_PENDING_CATALOG",moduleVersion:VERSION,approval:APPROVAL,previews,writes,audit,amazonPersistentWrites:writes.length,variationRelationWrites:writes.length,inventoryWrites:0,priceWrites:0,sellingPriceWrites:0,b2bWrites:0,adsWrites:0,yahooWrites:0,imageWrites:0,externalChanges:writes.length,doNotRetryAutomatically:!audit?.pass};}
setTimeout(()=>run().then(x=>console.log(`${TAG}=${JSON.stringify(x)}`)).catch(e=>console.error(`${ERR}=${JSON.stringify({moduleVersion:VERSION,error:e?.message||String(e),doNotRetryAutomatically:true,amazonPersistentWrites:0,inventoryWrites:0,priceWrites:0,b2bWrites:0,adsWrites:0,yahooWrites:0,externalChanges:0})}`)),7000);
