import "./s73_six_variation_fresh_audit_preload.mjs";
import fetch from "node-fetch";
import "dotenv/config";

const MARKETPLACE_ID="A1VC38T7YXB528";
const SKUS=["s73-hs-i5-11g-16gb-storage-parent","s73-hs-i5-11g-16gb-ssd512","7X-725F-2ZML"];
function j(t){try{return t?JSON.parse(t):{};}catch{return {rawText:String(t||"").slice(0,5000)};}}
async function token(){const r=await fetch("https://api.amazon.com/auth/o2/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({grant_type:"refresh_token",refresh_token:process.env.REFRESH_TOKEN,client_id:process.env.LWA_CLIENT_ID,client_secret:process.env.LWA_CLIENT_SECRET})});const x=j(await r.text());if(!r.ok||!x.access_token)throw new Error(`LWA_${r.status}`);return x.access_token;}
async function run(){const a=await token();const sellerId=String(process.env.SPAPI_SELLER_ID||"").trim();const endpoint=String(process.env.SPAPI_ENDPOINT||"https://sellingpartnerapi-fe.amazon.com").replace(/\/$/,"");const rows=[];for(const sku of SKUS){const q=new URLSearchParams({marketplaceIds:MARKETPLACE_ID,includedData:"summaries,attributes,issues,offers,fulfillmentAvailability",issueLocale:"ja_JP"});const r=await fetch(`${endpoint}/listings/2021-08-01/items/${encodeURIComponent(sellerId)}/${encodeURIComponent(sku)}?${q}`,{headers:{"x-amz-access-token":a,accept:"application/json"}});const b=j(await r.text());const at=b?.attributes||{};rows.push({sku,http:r.status,ok:r.ok,asin:b?.summaries?.[0]?.asin||"",title:b?.summaries?.[0]?.itemName||at?.item_name?.[0]?.value||"",parentage:at?.parentage_level?.[0]?.value||null,parentSku:at?.child_parent_sku_relationship?.[0]?.parent_sku||null,relationship:at?.child_parent_sku_relationship?.[0]?.child_relationship_type||null,theme:at?.variation_theme?.[0]?.name||null,hardDisk:at?.hard_disk||null,flashMemory:at?.flash_memory||null,packageDimensions:at?.item_package_dimensions||null,packageWeight:at?.item_package_weight||null,issues:Array.isArray(b?.issues)?b.issues:[]});}console.log("S73_VARIATION_POSTPARTIAL_AUDIT_RESULT="+JSON.stringify({readOnly:true,externalChanges:0,rows}));}
setTimeout(()=>run().catch(e=>console.error("S73_VARIATION_POSTPARTIAL_AUDIT_ERROR="+(e?.message||String(e)))),2500);
