import express from "express";
import fetch from "node-fetch";
import "dotenv/config";

const MODULE_VERSION="2026-09-12-s73-b2c-price-live-approved-v1.0.0";
const ROUTE="/amazon/price/s73/b2c-live-approved";
const LIVE_CONFIRM="S73_B2C_PRICE_6_LIVE_APPROVED_20260912";
const originalListen=express.application.listen;
const MARKETPLACE="A1VC38T7YXB528";
const TARGETS=Object.freeze([
 {sku:"s73-hs-i5-11g-8gb-ssd256",asin:"B0HJL5MCV9",price:35800,min:35500},
 {sku:"s73-hs-i5-11g-8gb-ssd512",asin:"B0HJLDDQQ3",price:49800,min:42400},
 {sku:"s73-hs-i5-11g-8gb-ssd1tb",asin:"B0HJL3QKXR",price:64800,min:56900},
 {sku:"7X-725F-2ZML",asin:"B0HGDBYRS8",price:43800,min:39600},
 {sku:"s73-hs-i5-11g-16gb-ssd512",asin:"B0HJ28YCP7",price:54800,min:54000},
 {sku:"s73-hs-i5-11g-16gb-ssd1tb",asin:"B0HJL1TP7L",price:69800,min:68500},
]);
const clone=v=>JSON.parse(JSON.stringify(v));
const parse=t=>{try{return t?JSON.parse(t):{};}catch{return {rawText:String(t||"").slice(0,1000)}}};
const audience=o=>String(o?.audience||"ALL").toUpperCase();
function cfg(){const sellerId=String(process.env.SPAPI_SELLER_ID||"").trim();if(!sellerId)throw new Error("Missing SPAPI_SELLER_ID");return {sellerId,marketplaceId:String(process.env.SPAPI_MARKETPLACE_ID||MARKETPLACE),endpoint:String(process.env.SPAPI_ENDPOINT||"https://sellingpartnerapi-fe.amazon.com").replace(/\/$/,"")};}
async function token(){const {LWA_CLIENT_ID,LWA_CLIENT_SECRET,REFRESH_TOKEN}=process.env;if(!LWA_CLIENT_ID||!LWA_CLIENT_SECRET||!REFRESH_TOKEN)throw new Error("Missing LWA env");const r=await fetch("https://api.amazon.com/auth/o2/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({grant_type:"refresh_token",refresh_token:REFRESH_TOKEN,client_id:LWA_CLIENT_ID,client_secret:LWA_CLIENT_SECRET})});const j=parse(await r.text());if(!r.ok||!j.access_token)throw new Error(`LWA ${r.status}`);return j.access_token;}
async function req(url,opt){const r=await fetch(url,opt);const j=parse(await r.text());if(!r.ok)throw new Error(`SPAPI ${r.status} ${JSON.stringify(j).slice(0,1600)}`);return {r,j};}
async function getListing(a,sku){const {sellerId,marketplaceId,endpoint}=cfg();const q=new URLSearchParams({marketplaceIds:marketplaceId,includedData:"summaries,attributes,issues,offers,fulfillmentAvailability",issueLocale:"ja_JP"});return (await req(`${endpoint}/listings/2021-08-01/items/${encodeURIComponent(sellerId)}/${encodeURIComponent(sku)}?${q}`,{headers:{"x-amz-access-token":a,accept:"application/json"}})).j;}
function consumerValue(price,min,marketplaceId){return {currency:"JPY",audience:"ALL",our_price:[{schedule:[{value_with_tax:price}]}],minimum_seller_allowed_price:[{schedule:[{value_with_tax:min}]}],marketplace_id:marketplaceId};}
function buildOffers(listing,t){const {marketplaceId}=cfg();const before=clone(Array.isArray(listing?.attributes?.purchasable_offer)?listing.attributes.purchasable_offer:[]);const after=clone(before);const beforeB2B=before.filter(o=>audience(o)==="B2B");let i=after.findIndex(o=>audience(o)!=="B2B");if(i<0){after.push(consumerValue(t.price,t.min,marketplaceId));}else{const c=after[i];c.currency=c.currency||"JPY";c.audience=c.audience||"ALL";c.marketplace_id=c.marketplace_id||marketplaceId;c.our_price=[{schedule:[{value_with_tax:t.price}]}];c.minimum_seller_allowed_price=[{schedule:[{value_with_tax:t.min}]}];}if(JSON.stringify(beforeB2B)!==JSON.stringify(after.filter(o=>audience(o)==="B2B")))throw new Error(`B2B_MUTATION ${t.sku}`);return after;}
async function patch(a,t,listing,preview){const {sellerId,marketplaceId,endpoint}=cfg();const q=new URLSearchParams({marketplaceIds:marketplaceId,issueLocale:"ja_JP"});if(preview)q.set("mode","VALIDATION_PREVIEW");const body={productType:String(listing?.summaries?.[0]?.productType||"NOTEBOOK_COMPUTER"),patches:[{op:"replace",path:"/attributes/purchasable_offer",value:buildOffers(listing,t)}]};const {r,j}=await req(`${endpoint}/listings/2021-08-01/items/${encodeURIComponent(sellerId)}/${encodeURIComponent(t.sku)}?${q}`,{method:"PATCH",headers:{"x-amz-access-token":a,accept:"application/json","content-type":"application/json"},body:JSON.stringify(body)});const issues=Array.isArray(j?.issues)?j.issues:[];const errors=issues.filter(x=>String(x?.severity||"").toUpperCase()==="ERROR");return {http:r.status,status:String(j?.status||""),submissionId:String(j?.submissionId||""),errors,issueCodes:issues.map(x=>String(x?.code||"")).filter(Boolean)};}
async function handler(req,res){let liveCalls=0;try{const secret=String(process.env.AMAZON_STOCK_API_SECRET||"").trim();if(!secret)return res.status(500).json({ok:false,decision:"CONFIG_ERROR",liveCalls:0,externalChanges:0});if(String(req.headers["x-api-secret"]||"")!==secret)return res.status(401).json({ok:false,decision:"UNAUTHORIZED",liveCalls:0,externalChanges:0});if(String(req.body?.liveConfirm||"")!==LIVE_CONFIRM)return res.status(400).json({ok:false,decision:"LIVE_CONFIRM_MISMATCH",liveCalls:0,externalChanges:0});const a=await token();const results=[];for(const t of TARGETS){const listing=await getListing(a,t.sku);const asin=String(listing?.summaries?.[0]?.asin||"");if(asin!==t.asin)throw new Error(`ASIN_MISMATCH ${t.sku} ${asin}`);const preview=await patch(a,t,listing,true);if(preview.errors.length)throw new Error(`PREVIEW_FAILED ${t.sku} ${preview.issueCodes.join(",")}`);const fresh=await getListing(a,t.sku);const live=await patch(a,t,fresh,false);liveCalls+=1;if(live.errors.length)throw new Error(`LIVE_RESPONSE_ERROR ${t.sku} ${live.issueCodes.join(",")}`);results.push({sku:t.sku,asin:t.asin,targetPrice:t.price,targetMin:t.min,previewStatus:preview.status,liveStatus:live.status,submissionId:live.submissionId});}return res.status(200).json({ok:true,moduleVersion:MODULE_VERSION,route:ROUTE,decision:"S73_B2C_PRICE_6_LIVE_SUBMITTED",liveCalls,persistentAmazonWrites:liveCalls,externalChanges:liveCalls,scope:{consumerOurPrice:true,consumerMinimum:true,b2b:false,inventory:false,content:false,variation:false,listPrice:false,ads:false,yahoo:false},results});}catch(err){return res.status(500).json({ok:false,moduleVersion:MODULE_VERSION,route:ROUTE,decision:liveCalls?"STOP_AFTER_PARTIAL_LIVE_DO_NOT_RERUN":"STOP_BEFORE_LIVE",liveCalls,persistentAmazonWrites:liveCalls,externalChanges:liveCalls,error:err?.message||String(err)});}}
express.application.listen=function s73B2CLiveApprovedListen(...args){const exists=Boolean(this?._router?.stack?.some(layer=>layer?.route?.path===ROUTE));if(!exists)this.post(ROUTE,handler);return originalListen.apply(this,args);};
