import express from "express";
import fetch from "node-fetch";
import "dotenv/config";

const MODULE_VERSION="2026-09-24-x13-s73-price-test-preflight-v1.1.0";
const ROUTE="/amazon/price/price-test/x13-s73/preflight";
const TARGETS=Object.freeze({
  "NY-G14F-GH8Y":Object.freeze({sku:"NY-G14F-GH8Y",asin:"B0FMS8XJ3D",normalPrice:34900,salePrice:32800,safeFloor:30000,durationHours:168}),
  "s73-hs-i5-11g-8gb-ssd1tb":Object.freeze({sku:"s73-hs-i5-11g-8gb-ssd1tb",asin:"B0HJL3QKXR",normalPrice:64800,salePrice:59000,safeFloor:58600,durationHours:168})
});
const originalPost=express.application.post;
const TIMEOUT=20000;
const clone=x=>JSON.parse(JSON.stringify(x));
const num=v=>v===null||v===undefined||v===""?null:(Number.isFinite(Number(v))?Number(v):null);
const epoch=v=>{const t=Date.parse(String(v||""));return Number.isFinite(t)?t:null;};
const json=t=>{try{return JSON.parse(t||"{}")}catch{return{rawText:t}}};
function cfg(){const sellerId=String(process.env.SPAPI_SELLER_ID||"").trim(),marketplaceId=String(process.env.SPAPI_MARKETPLACE_ID||"A1VC38T7YXB528").trim(),endpoint=String(process.env.SPAPI_ENDPOINT||"https://sellingpartnerapi-fe.amazon.com").replace(/\/$/,"");if(!sellerId)throw new Error("Missing SPAPI_SELLER_ID");return{sellerId,marketplaceId,endpoint};}
async function token(){const r=await fetch("https://api.amazon.com/auth/o2/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({grant_type:"refresh_token",refresh_token:process.env.REFRESH_TOKEN,client_id:process.env.LWA_CLIENT_ID,client_secret:process.env.LWA_CLIENT_SECRET})});const j=json(await r.text());if(!r.ok||!j.access_token)throw new Error("LWA token error:"+r.status);return j.access_token;}
async function req(url,a,opt={}){const c=new AbortController(),tm=setTimeout(()=>c.abort(),TIMEOUT);try{const r=await fetch(url,{...opt,headers:{"x-amz-access-token":a,accept:"application/json",...(opt.body?{"content-type":"application/json"}:{}),...(opt.headers||{})},signal:c.signal});const j=json(await r.text());if(!r.ok)throw new Error("SPAPI "+r.status+" "+JSON.stringify(j));return j;}finally{clearTimeout(tm);}}
async function listing(a,spec){const {sellerId,marketplaceId,endpoint}=cfg(),q=new URLSearchParams({marketplaceIds:marketplaceId,includedData:"summaries,attributes,issues,fulfillmentAvailability",issueLocale:"ja_JP"});return req(`${endpoint}/listings/2021-08-01/items/${encodeURIComponent(sellerId)}/${encodeURIComponent(spec.sku)}?${q}`,a);}
function schedules(o,k){return Array.isArray(o?.[k]?.[0]?.schedule)?o[k][0].schedule:[];}
function active(o,k,now){return schedules(o,k).filter(s=>{const st=epoch(s?.start_at),en=epoch(s?.end_at);return !(st!==null&&now<st)&&!(en!==null&&now>=en);}).sort((a,b)=>(epoch(b?.start_at)??0)-(epoch(a?.start_at)??0))[0]||null;}
function snap(spec,l,now=Date.now()){const s=Array.isArray(l?.summaries)?l.summaries[0]||{}:{},at=l?.attributes||{},issues=Array.isArray(l?.issues)?l.issues:[],offers=Array.isArray(at?.purchasable_offer)?clone(at.purchasable_offer):[],ci=offers.findIndex(x=>String(x?.audience||"ALL").toUpperCase()==="ALL"),c=ci>=0?offers[ci]:null,avail=Array.isArray(l?.fulfillmentAvailability)?l.fulfillmentAvailability[0]||{}:{};return{spec,asin:String(s?.asin||""),productType:String(s?.productType||""),statuses:Array.isArray(s?.status)?s.status.map(String):[],errorCount:issues.filter(x=>String(x?.severity||"").toUpperCase()==="ERROR").length,qty:num(avail?.quantity)??num(at?.fulfillment_availability?.[0]?.quantity)??0,offers,consumerIndex:ci,consumer:c,normal:num(active(c,"our_price",now)?.value_with_tax),sale:num(active(c,"discounted_price",now)?.value_with_tax),min:num(active(c,"minimum_seller_allowed_price",now)?.value_with_tax)};}
function guard(st){const s=st.spec,b=[];if(st.asin!==s.asin)b.push("ASIN:"+st.asin);if(!st.productType)b.push("PRODUCT_TYPE_MISSING");if(!st.statuses.includes("BUYABLE"))b.push("NOT_BUYABLE");if(st.errorCount)b.push("LISTING_ERRORS:"+st.errorCount);if(!(st.qty>0))b.push("NO_STOCK");if(!st.consumer||st.consumerIndex<0)b.push("CONSUMER_OFFER_MISSING");if(st.normal!==s.normalPrice)b.push("NORMAL_DRIFT:"+st.normal);if(st.sale!==null)b.push("ACTIVE_SALE_PRESENT:"+st.sale);if(!(st.min>0))b.push("MIN_MISSING");if(st.min>s.salePrice)b.push("AMAZON_MIN_ABOVE_TEST:"+st.min);if(s.salePrice<s.safeFloor)b.push("TEST_BELOW_SAFE_FLOOR");return b;}
function build(st,now){const s=st.spec,offers=clone(st.offers),before=clone(st.offers),c=offers[st.consumerIndex],startAt=new Date(now-60000).toISOString(),endAt=new Date(now+s.durationHours*3600000).toISOString();c.discounted_price=[{schedule:[{value_with_tax:s.salePrice,start_at:startAt,end_at:endAt}]}];const b0=clone(before),a0=clone(offers);if(b0[st.consumerIndex])delete b0[st.consumerIndex].discounted_price;if(a0[st.consumerIndex])delete a0[st.consumerIndex].discounted_price;if(JSON.stringify(b0)!==JSON.stringify(a0))throw new Error("NON_SALE_ATTRIBUTE_MUTATION_DETECTED");return{startAt,endAt,body:{productType:st.productType,patches:[{op:"replace",path:"/attributes/purchasable_offer",value:offers}]}};}
async function preview(a,st,p){const {sellerId,marketplaceId,endpoint}=cfg(),q=new URLSearchParams({marketplaceIds:marketplaceId,issueLocale:"ja_JP",mode:"VALIDATION_PREVIEW"}),j=await req(`${endpoint}/listings/2021-08-01/items/${encodeURIComponent(sellerId)}/${encodeURIComponent(st.spec.sku)}?${q}`,a,{method:"PATCH",body:JSON.stringify(p.body)}),issues=Array.isArray(j?.issues)?j.issues:[],errors=issues.filter(x=>String(x?.severity||"").toUpperCase()==="ERROR");return{status:String(j?.status||""),submissionId:String(j?.submissionId||""),issues,errorCount:errors.length,valid:errors.length===0&&["VALID","ACCEPTED"].includes(String(j?.status||"").toUpperCase())};}
async function handler(req,res){try{const secret=String(process.env.AMAZON_STOCK_API_SECRET||"").trim();if(!secret)return res.status(500).json({ok:false,moduleVersion:MODULE_VERSION,externalChanges:0,error:"SECRET_MISSING"});if(String(req.headers["x-api-secret"]||"")!==secret)return res.status(401).json({ok:false,moduleVersion:MODULE_VERSION,externalChanges:0,error:"UNAUTHORIZED"});if(req.body?.dryRun!==true)return res.status(400).json({ok:false,moduleVersion:MODULE_VERSION,externalChanges:0,error:"dryRun=true required"});const requested=Array.isArray(req.body?.skus)?req.body.skus.map(String):Object.keys(TARGETS),unknown=requested.filter(x=>!TARGETS[x]);if(unknown.length||requested.length!==2)return res.status(400).json({ok:false,moduleVersion:MODULE_VERSION,externalChanges:0,error:"EXACT_SCOPE_TWO_SKUS_REQUIRED",unknown});const a=await token(),now=Date.now(),rows=[];for(const sku of requested){const spec=TARGETS[sku],st=snap(spec,await listing(a,spec),now),blocks=guard(st);if(blocks.length){rows.push({sku,asin:spec.asin,blocks,state:{normalPrice:st.normal,activeSalePrice:st.sale,minimumSellerAllowedPrice:st.min,availableQuantity:st.qty,statuses:st.statuses}});continue;}const p=build(st,now),v=await preview(a,st,p);rows.push({sku,asin:spec.asin,blocks:[],target:{salePrice:spec.salePrice,safeFloor:spec.safeFloor,durationHours:spec.durationHours,startAt:p.startAt,endAt:p.endAt},validation:v,state:{normalPrice:st.normal,activeSalePrice:st.sale,minimumSellerAllowedPrice:st.min,availableQuantity:st.qty,statuses:st.statuses}});}const ok=rows.length===2&&rows.every(x=>!x.blocks.length&&x.validation?.valid);return res.status(ok?200:409).json({ok,moduleVersion:MODULE_VERSION,route:ROUTE,decision:ok?"PRICE_TEST_VALIDATION_PREVIEW_ALL_2_PASS":"PRICE_TEST_VALIDATION_PREVIEW_BLOCK",validationPreviewCalls:rows.filter(x=>x.validation).length,persistentAmazonWrites:0,liveCalls:0,externalChanges:0,rows,liveAllowed:false,liveBlockedReason:"EXPLICIT_USER_LIVE_APPROVAL_REQUIRED"});}catch(e){return res.status(500).json({ok:false,moduleVersion:MODULE_VERSION,route:ROUTE,persistentAmazonWrites:0,liveCalls:0,externalChanges:0,error:e?.message||String(e)});}}
express.application.post=function(path,...handlers){return originalPost.call(this,path,...handlers);};
const originalUse=express.application.use;
express.application.use=function(...args){const r=originalUse.apply(this,args);if(!this.__x13S73PriceTestPreflight){this.__x13S73PriceTestPreflight=true;originalPost.call(this,ROUTE,handler);console.log(`${MODULE_VERSION} route installed: POST ${ROUTE}`);}return r;};
