import express from "express";
import fetch from "node-fetch";
import "dotenv/config";

const MODULE_VERSION="2026-09-24-x13-s73-price-test-live-v1.0.0";
const ROUTE="/amazon/price/price-test/x13-s73/live";
const CONFIRM="X13_S73_PRICE_TEST_7D_LIVE_APPROVED_20260924_V1";
const TARGETS=Object.freeze([
  Object.freeze({sku:"NY-G14F-GH8Y",asin:"B0FMS8XJ3D",normalPrice:34900,salePrice:32800,safeFloor:30000,durationHours:168}),
  Object.freeze({sku:"s73-hs-i5-11g-8gb-ssd1tb",asin:"B0HJL3QKXR",normalPrice:64800,salePrice:59000,safeFloor:58600,durationHours:168})
]);
const VERIFY_ATTEMPTS=8, VERIFY_WAIT_MS=1800, TIMEOUT=20000;
const originalUse=express.application.use;
const clone=x=>JSON.parse(JSON.stringify(x));
const num=v=>v===null||v===undefined||v===""?null:(Number.isFinite(Number(v))?Number(v):null);
const epoch=v=>{const t=Date.parse(String(v||""));return Number.isFinite(t)?t:null;};
const json=t=>{try{return JSON.parse(t||"{}")}catch{return{rawText:t}}};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function cfg(){const sellerId=String(process.env.SPAPI_SELLER_ID||"").trim(),marketplaceId=String(process.env.SPAPI_MARKETPLACE_ID||"A1VC38T7YXB528").trim(),endpoint=String(process.env.SPAPI_ENDPOINT||"https://sellingpartnerapi-fe.amazon.com").replace(/\/$/,"");if(!sellerId)throw new Error("Missing SPAPI_SELLER_ID");return{sellerId,marketplaceId,endpoint};}
async function token(){const r=await fetch("https://api.amazon.com/auth/o2/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({grant_type:"refresh_token",refresh_token:process.env.REFRESH_TOKEN,client_id:process.env.LWA_CLIENT_ID,client_secret:process.env.LWA_CLIENT_SECRET})});const j=json(await r.text());if(!r.ok||!j.access_token)throw new Error("LWA token error:"+r.status);return j.access_token;}
async function req(url,a,opt={}){const c=new AbortController(),tm=setTimeout(()=>c.abort(),TIMEOUT);try{const r=await fetch(url,{...opt,headers:{"x-amz-access-token":a,accept:"application/json",...(opt.body?{"content-type":"application/json"}:{}),...(opt.headers||{})},signal:c.signal});const j=json(await r.text());if(!r.ok)throw new Error("SPAPI "+r.status+" "+JSON.stringify(j));return j;}finally{clearTimeout(tm);}}
async function listing(a,spec){const {sellerId,marketplaceId,endpoint}=cfg(),q=new URLSearchParams({marketplaceIds:marketplaceId,includedData:"summaries,attributes,issues,fulfillmentAvailability",issueLocale:"ja_JP"});return req(`${endpoint}/listings/2021-08-01/items/${encodeURIComponent(sellerId)}/${encodeURIComponent(spec.sku)}?${q}`,a);}
function schedules(o,k){return Array.isArray(o?.[k]?.[0]?.schedule)?o[k][0].schedule:[];}
function active(o,k,now){return schedules(o,k).filter(s=>{const st=epoch(s?.start_at),en=epoch(s?.end_at);return !(st!==null&&now<st)&&!(en!==null&&now>=en);}).sort((a,b)=>(epoch(b?.start_at)??0)-(epoch(a?.start_at)??0))[0]||null;}
function snap(spec,l,now=Date.now()){const s=Array.isArray(l?.summaries)?l.summaries[0]||{}:{},at=l?.attributes||{},issues=Array.isArray(l?.issues)?l.issues:[],offers=Array.isArray(at?.purchasable_offer)?clone(at.purchasable_offer):[],ci=offers.findIndex(x=>String(x?.audience?.value||x?.audience||"ALL").toUpperCase()==="ALL"),c=ci>=0?offers[ci]:null,avail=Array.isArray(l?.fulfillmentAvailability)?l.fulfillmentAvailability[0]||{}:{};return{spec,asin:String(s?.asin||""),productType:String(s?.productType||""),statuses:Array.isArray(s?.status)?s.status.map(String):[],errorCount:issues.filter(x=>String(x?.severity||"").toUpperCase()==="ERROR").length,qty:num(avail?.quantity)??num(at?.fulfillment_availability?.[0]?.quantity)??0,offers,consumerIndex:ci,consumer:c,normal:num(active(c,"our_price",now)?.value_with_tax),sale:num(active(c,"discounted_price",now)?.value_with_tax),saleStart:String(active(c,"discounted_price",now)?.start_at||""),saleEnd:String(active(c,"discounted_price",now)?.end_at||""),min:num(active(c,"minimum_seller_allowed_price",now)?.value_with_tax)};}
function guard(st,allowApplied=false){const s=st.spec,b=[];if(st.asin!==s.asin)b.push("ASIN:"+st.asin);if(!st.productType)b.push("PRODUCT_TYPE_MISSING");if(!st.statuses.includes("BUYABLE"))b.push("NOT_BUYABLE");if(st.errorCount)b.push("LISTING_ERRORS:"+st.errorCount);if(!(st.qty>0))b.push("NO_STOCK");if(!st.consumer||st.consumerIndex<0)b.push("CONSUMER_OFFER_MISSING");if(st.normal!==s.normalPrice)b.push("NORMAL_DRIFT:"+st.normal);if(!allowApplied&&st.sale!==null)b.push("ACTIVE_SALE_PRESENT:"+st.sale);if(!(st.min>0))b.push("MIN_MISSING");if(st.min>s.salePrice)b.push("AMAZON_MIN_ABOVE_TEST:"+st.min);if(s.salePrice<s.safeFloor)b.push("TEST_BELOW_SAFE_FLOOR");return b;}
function build(st,startAt,endAt){const s=st.spec,offers=clone(st.offers),before=clone(st.offers),c=offers[st.consumerIndex];c.discounted_price=[{schedule:[{value_with_tax:s.salePrice,start_at:startAt,end_at:endAt}]}];const b0=clone(before),a0=clone(offers);if(b0[st.consumerIndex])delete b0[st.consumerIndex].discounted_price;if(a0[st.consumerIndex])delete a0[st.consumerIndex].discounted_price;if(JSON.stringify(b0)!==JSON.stringify(a0))throw new Error("NON_SALE_ATTRIBUTE_MUTATION_DETECTED");return{productType:st.productType,patches:[{op:"replace",path:"/attributes/purchasable_offer",value:offers}]};}
async function patch(a,st,body,preview){const {sellerId,marketplaceId,endpoint}=cfg(),q=new URLSearchParams({marketplaceIds:marketplaceId,issueLocale:"ja_JP"});if(preview)q.set("mode","VALIDATION_PREVIEW");const j=await req(`${endpoint}/listings/2021-08-01/items/${encodeURIComponent(sellerId)}/${encodeURIComponent(st.spec.sku)}?${q}`,a,{method:"PATCH",body:JSON.stringify(body)}),issues=Array.isArray(j?.issues)?j.issues:[],errors=issues.filter(x=>String(x?.severity||"").toUpperCase()==="ERROR");return{status:String(j?.status||""),submissionId:String(j?.submissionId||""),issues,errorCount:errors.length,valid:errors.length===0&&["VALID","ACCEPTED"].includes(String(j?.status||"").toUpperCase())};}
async function verify(a,spec,startAt,endAt){let last=null;for(let i=1;i<=VERIFY_ATTEMPTS;i++){last=snap(spec,await listing(a,spec),Date.now());if(last.normal===spec.normalPrice&&last.sale===spec.salePrice&&last.saleStart===startAt&&last.saleEnd===endAt)return{verified:true,attempt:i,state:{normalPrice:last.normal,activeSalePrice:last.sale,saleStart:last.saleStart,saleEnd:last.saleEnd,minimumSellerAllowedPrice:last.min,availableQuantity:last.qty,statuses:last.statuses}};if(i<VERIFY_ATTEMPTS)await sleep(VERIFY_WAIT_MS);}return{verified:false,attempt:VERIFY_ATTEMPTS,state:last?{normalPrice:last.normal,activeSalePrice:last.sale,saleStart:last.saleStart,saleEnd:last.saleEnd,minimumSellerAllowedPrice:last.min,availableQuantity:last.qty,statuses:last.statuses}:null};}
async function handler(req,res){let liveCalls=0;const completed=[];try{const secret=String(process.env.AMAZON_STOCK_API_SECRET||"").trim();if(!secret)return res.status(500).json({ok:false,moduleVersion:MODULE_VERSION,liveCalls,externalChanges:liveCalls,error:"SECRET_MISSING"});if(String(req.headers["x-api-secret"]||"")!==secret)return res.status(401).json({ok:false,moduleVersion:MODULE_VERSION,liveCalls,externalChanges:liveCalls,error:"UNAUTHORIZED"});if(String(req.body?.confirm||"")!==CONFIRM)return res.status(400).json({ok:false,moduleVersion:MODULE_VERSION,liveCalls,externalChanges:liveCalls,error:"CONFIRM_MISMATCH",requiredConfirm:CONFIRM});const a=await token(),now=Date.now(),startAt=new Date(now-60000).toISOString(),endAt=new Date(now+168*3600000).toISOString();
const first=[];for(const spec of TARGETS){const st=snap(spec,await listing(a,spec),now),blocks=guard(st,false);first.push({spec,st,blocks});}const preBlocks=first.filter(x=>x.blocks.length).map(x=>({sku:x.spec.sku,blocks:x.blocks}));if(preBlocks.length)return res.status(409).json({ok:false,moduleVersion:MODULE_VERSION,decision:"PREFLIGHT_BLOCKED_NO_LIVE",preBlocks,liveCalls:0,persistentAmazonWrites:0,externalChanges:0});
let validationPreviewCalls=0;for(const x of first){const v=await patch(a,x.st,build(x.st,startAt,endAt),true);validationPreviewCalls++;if(!v.valid)return res.status(422).json({ok:false,moduleVersion:MODULE_VERSION,decision:"VALIDATION_PREVIEW_FAILED_NO_LIVE",sku:x.spec.sku,validation:v,validationPreviewCalls,liveCalls:0,persistentAmazonWrites:0,externalChanges:0});}
const second=[];for(const spec of TARGETS){const st=snap(spec,await listing(a,spec),Date.now()),blocks=guard(st,false);second.push({spec,st,blocks});}const freshBlocks=second.filter(x=>x.blocks.length).map(x=>({sku:x.spec.sku,blocks:x.blocks}));if(freshBlocks.length)return res.status(409).json({ok:false,moduleVersion:MODULE_VERSION,decision:"SECOND_PREFLIGHT_BLOCKED_NO_LIVE",freshBlocks,validationPreviewCalls,liveCalls:0,persistentAmazonWrites:0,externalChanges:0});
for(const x of second){const accepted=await patch(a,x.st,build(x.st,startAt,endAt),false);liveCalls++;if(!accepted.valid)return res.status(409).json({ok:false,moduleVersion:MODULE_VERSION,decision:"LIVE_NOT_ACCEPTED_DO_NOT_RETRY_BATCH",activeLiveSku:x.spec.sku,accepted,completed,validationPreviewCalls,liveCalls,persistentAmazonWrites:liveCalls,externalChanges:liveCalls});const vr=await verify(a,x.spec,startAt,endAt);if(!vr.verified)return res.status(202).json({ok:false,moduleVersion:MODULE_VERSION,decision:"LIVE_SUBMITTED_POSTVERIFY_INCOMPLETE_DO_NOT_RERUN_BATCH",activeLiveSku:x.spec.sku,completed,validationPreviewCalls,liveCalls,persistentAmazonWrites:liveCalls,externalChanges:liveCalls,verify:vr,nextStep:"FRESH_AUDIT_ONLY_DO_NOT_RERUN_BATCH"});completed.push({sku:x.spec.sku,asin:x.spec.asin,targetSale:x.spec.salePrice,verified:true,verifyAttempt:vr.attempt});}
return res.status(200).json({ok:true,moduleVersion:MODULE_VERSION,route:ROUTE,decision:"LIVE_X13_S73_PRICE_TEST_ALL_2_VERIFIED",startAt,endAt,validationPreviewCalls,liveCalls,persistentAmazonWrites:liveCalls,externalChanges:liveCalls,completed});
}catch(e){return res.status(500).json({ok:false,moduleVersion:MODULE_VERSION,route:ROUTE,decision:"ERROR",error:e?.message||String(e),completed,liveCalls,persistentAmazonWrites:liveCalls,externalChanges:liveCalls});}}
express.application.use=function(...args){const r=originalUse.apply(this,args);if(!this.__x13S73PriceTestLive){this.__x13S73PriceTestLive=true;this.post(ROUTE,handler);console.log(`${MODULE_VERSION} route installed: POST ${ROUTE}`);}return r;};
